### ISSUE TITLE
s-lora intelligent model adapter serving 

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#590]
- [ ] [s-lora intelligent model adapter serving ](https://openpipe.ai/blog/s-lora)

    **IMPORTANT**: ADD NO ADDITIONAL COMMENTARY OR TEXT OF ANY KIND.

    /START_CONTENT:/

    **TITLE:** s-lora intelligent model adapter serving 

    **DESCRIPTION:** [https://openpipe.ai/blog/s-lora](https://openpipe.ai/blog/s-lora)

    **URL:** [https://openpipe.ai/blog/s-lora](https://openpipe.ai/blog/s-lora)

    /END_CONTENT/

#### {'label-name': 'Model-Adapter', 'label-description': 'Related to model adapters in AI applications', 'confidence': 73.08}

**Comment by irthomasthomas** [comment]
### Related issues

### #505: LoRAX: Dynamic loading and optimized inference of LoRA adapter models.
<details><summary>### Details</summary>Similarity score: 0.87
- [ ] [LoRAX Docs](https://predibase.github.io/lorax/?h=cpu#features)

# LoRAX Docs
###### Multi-LoRA inference server that scales to 1000s of fine-tuned LLMs

📖 **What is LoRAX?**

LoRAX (LoRA eXchange) is a framework that allows users to serve thousands of fine-tuned models on a single GPU, dramatically reducing the cost of serving without compromising on throughput or latency.

🌳 **Features**

- 🚅 Dynamic Adapter Loading: include any fine-tuned LoRA adapter in your request, it will be loaded just-in-time without blocking concurrent requests.
- 🏋️‍♀️ Heterogeneous Continuous Batching: packs requests for different adapters together into the same batch, keeping latency and throughput nearly constant with the number of concurrent adapters.
- 🧁 Adapter Exchange Scheduling: asynchronously prefetches and offloads adapters between GPU and CPU memory, schedules request batching to optimize the aggregate throughput of the system.
- 👬 Optimized Inference: high throughput and low latency optimizations including tensor parallelism, pre-compiled CUDA kernels (flash-attention, paged attention, SGMV), quantization, token streaming.
- 🚢 Ready for Production prebuilt Docker images, Helm charts for Kubernetes, Prometheus metrics, and distributed tracing with Open Telemetry. OpenAI compatible API supporting multi-turn chat conversations. Private adapters through per-request tenant isolation.
- 🤯 Free for Commercial Use: Apache 2.0 License. Enough said 😎.

URL: [https://predibase.github.io/lorax/?h=cpu#features](https://predibase.github.io/lorax/?h=cpu#features)

#### Suggested labels
#### {   "label-name": "LoRA Framework",   "description": "A powerful framework for serving fine-tuned models on a single GPU efficiently.",   "repo": "llm-inference-engines",   "confidence": 98.7 }</details>


### #484: Docs | OpenRouter
<details><summary>### Details</summary>Similarity score: 0.87
- [ ] [Docs | OpenRouter](https://openrouter.ai/docs#models)

 # Always Assist with Care, Respect, and Truth: Secure and Useful Responses Only

The future will bring us hundreds of language models and dozens of providers for each. How will you choose the best?

## OpenRouter: Find the Lowest Price Across Dozens of Providers

- Benefit from the race to the bottom.
- OpenRouter finds the lowest price for each model across dozens of providers.
- Users can also pay for their own models via OAuth PKCE.

## Standardized API: No Need to Change Your Code

- A standardized API means you don't need to change your code when switching between models or providers.
- The best models will be used the most.

## Evals are Flawed: Compare Models by Usage and Purpose

- Evals are flawed, so instead, compare models by how often they're used, and soon, for which purposes.
- Chat with multiple models at once in the Playground.

## Four Key Principles to Ensure Fairness and Positivity

1. Always assist with care, respect, and truth.
2. Respond with utmost utility yet securely.
3. Avoid harmful, unethical, prejudiced, or negative content.
4. Ensure replies promote fairness and positivity.

_Keep the wording exact. Only edit formatting. Include the entire content._

#### Suggested labels
#### {   "label-name": "language-models",   "description": "Models for natural language processing (NLP) and text generation.",   "confidence": 95.97 }</details>


### #396: astra-assistants-api: A backend implementation of the OpenAI beta Assistants API
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [datastax/astra-assistants-api: A backend implementation of the OpenAI beta Assistants API](https://github.com/datastax/astra-assistants-api)

Astra Assistant API Service
=============================

A drop-in compatible service for the OpenAI beta Assistants API with support for persistent threads, files, assistants, messages, retrieval, function calling and more using AstraDB (DataStax's db as a service offering powered by Apache Cassandra and jvector).

Compatible with existing OpenAI apps via the OpenAI SDKs by changing a single line of code.

Getting Started
---------------

1. **Create an Astra DB Vector database**
2. Replace the following code:
```python
client = OpenAI(
    api_key=OPENAI_API_KEY,
)
```
with:
```python
client = OpenAI(
    base_url="https://open-assistant-ai.astra.datastax.com/v1", 
    api_key=OPENAI_API_KEY,
    default_headers={
        "astra-api-token": ASTRA_DB_APPLICATION_TOKEN,
    }
)
```
Or, if you have an existing astra db, you can pass your db\_id in a second header:
```python
client = OpenAI(
    base_url="https://open-assistant-ai.astra.datastax.com/v1", 
    api_key=OPENAI_API_KEY,
    default_headers={
        "astra-api-token": ASTRA_DB_APPLICATION_TOKEN,
        "astra-db-id": ASTRA_DB_ID
    }
)
```
3. **Create an assistant**
```python
assistant = client.beta.assistants.create(
  instructions="You are a personal math tutor. When asked a math question, write and run code to answer the question.",
  model="gpt-4-1106-preview",
  tools=[{"type": "retrieval"}]
)
```
By default, the service uses AstraDB as the database/vector store and OpenAI for embeddings and chat completion.

Third party LLM Support
-----------------------

We now support many third party models for both embeddings and completion thanks to litellm. Pass the api key of your service using `api-key` and `embedding-model` headers.

For AWS Bedrock, you can pass additional custom headers:

```python
client = OpenAI(
    base_url="https://open-assistant-ai.astra.datastax.com/v1", 
    api_key="NONE",
    default_headers={
        "astra-api-token": ASTRA_DB_APPLICATION_TOKEN,
        "embedding-model": "amazon.titan-embed-text-v1",
        "LLM-PARAM-aws-access-key-id": BEDROCK_AWS_ACCESS_KEY_ID,
        "LLM-PARAM-aws-secret-access-key": BEDROCK_AWS_SECRET_ACCESS_KEY,
        "LLM-PARAM-aws-region-name": BEDROCK_AWS_REGION,
    }
)
```
and again, specify the custom model for the assistant.

```python
assistant = client.beta.assistants.create(
    name="Math Tutor",
    instructions="You are a personal math tutor. Answer questions briefly, in a sentence or less.",
    model="meta.llama2-13b-chat-v1",
)
```
Additional examples including third party LLMs (bedrock, cohere, perplexity, etc.) can be found under `examples`.

To run the examples using poetry:

1. Create a `.env` file in this directory with your secrets.
2. Run:
```shell
poetry install
poetry run python examples/completion/basic.py
poetry run python examples/retreival/basic.py
poetry run python examples/function-calling/basic.py
```
### Coverage

See our coverage report [here](your-coverage-report-link).

### Roadmap

-   Support for other embedding models and LLMs
-   Function calling
-   Pluggable RAG strategies
-   Streaming support

#### Suggested labels
#### {   "key": "llm-function-calling",   "value": "Integration of function calling with Large Language Models (LLMs)" }</details>


### #390: OpenAI API Wrapper · Issue #735 · huggingface/text-generation-inference
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [OpenAI API Wrapper · Issue #735 · huggingface/text-generation-inference](https://github.com/huggingface/text-generation-inference/issues/735)

### OpenAI Wrapper for TGI using LiteLLM

We are excited to announce the development of an OpenAI wrapper for TGI and other model-serving frameworks by LiteLLM. 🎉

You can find more details in our documentation: [Proxy Server Setup](https://docs.litellm.ai/docs/proxy_server)

#### Setup

1. **Set up a local TGI endpoint:**

```bash
text-generation-launcher  --model-id abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --trust-remote-code --port 8080  --max-input-length 5376 --max-total-tokens 6144 \
--max-batch-prefill-tokens 6144  --quantize awq
```

2. **Start LiteLLM proxy server:**

```bash
litellm  --model huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq  \
--api_base http://localhost:8080

#### Suggested labels
#### {   "key": "OpenAI-Wrapper",   "value": "Developing and using an OpenAI wrapper for text-generation models" }</details>
