### ISSUE TITLE
You (Probably) Shouldn't use a Lookup Table

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#689]
- [ ] [You (Probably) Shouldn't use a Lookup Table](https://specbranch.com/posts/lookup-tables/)

# You (Probably) Shouldn't use a Lookup Table

**DESCRIPTION:** SPECULATIVE BRANCHES  
THOUGHTS ON SOFTWARE, HARDWARE, PERFORMANCE, MATH, AND SIMILAR TOPICS  
HOME  
ABOUT ME  
CATEGORIES  
TAGS  
CONSULTING  

I have been working on another post recently, also related to division, but I wanted to address a comment I got from several people on the previous division article. This comment invariably follows a lot of articles on using math to do things with chars and shorts. It is: “why are you doing all of this when you can just use a lookup table?”

Even worse, a stubborn and clever commenter may show you a benchmark where your carefully-crafted algorithm performs worse than their hamfisted lookup table. Surely you have made a mistake and you should just use a lookup table. Just look at the benchmark!

When you have only 8 or 16 bits of arguments, it is tempting to precompute all of the answers and throw them in a lookup table. After all, a table of 256 8-bit numbers is only 256 bytes, and even 65536 16-bit numbers is well under a megabyte. Both are a rounding error compared to the memory and code footprints of software today. A lookup table is really easy to generate, and it’s just one memory access to find the answer, right?

The correct response to the lookup table question is the following: If you care about performance, you should almost never use a lookup table algorithm, despite what a microbenchmark might say.

**URL:** [https://specbranch.com/posts/lookup-tables/](https://specbranch.com/posts/lookup-tables/)

#### {'label-name': 'performance', 'label-description': 'Analyzing software efficiency and speed considerations', 'confidence': 64.93}

**Comment by irthomasthomas** [comment]
### Related content
### #655: At the Intersection of LLMs and Kernels - Research Roundup
<details><summary>### Details</summary>Similarity score: 0.83
- [ ] [At the Intersection of LLMs and Kernels - Research Roundup](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

# At the Intersection of LLMs and Kernels - Research Roundup

**DESCRIPTION:**  
"At the Intersection of LLMs and Kernels - Research Roundup  
Nov 10, 2023

Relational databases like postgreSQL and operating system kernels like Linux are foundational building blocks for computing systems. Every “application” is in essence an “application” of those building blocks to some purpose: Twitter applies databases to write and read tweets; it applies an operating system to operate the hardware required to do so.

Large language models – and large generative models of complex data types more broadly – are a new building block at this foundational layer. ML researchers like me have many useful intuitions about what can be built with this novel building block and how to improve it.

But the people who have spent years building with those other blocks have many more. Many of these inuitions are surprising to someone who has spent more time with neural networks than with the network stack.

This post is a collection of short explainers for papers that directly draw from systems metaphors in designing improvements for LLMs, ranging from novel approaches to pretraining to inference-time speed optimizations.

Perhaps most interesting are prompting strategies that make LLMs act more like kernels.

It is intended to get researchers and hackers of LLMs interested in systems and vice versa.

We’ll proceed by first introducing an idea from the systems level – roughly, the interface of hardware, kernel, and application – and then showing how it has been applied to LLMs in recent research.

Update 2023-12-30: the topics discussed here are also covered in this recorded talk from the Scale By The Bay 2023 conference.

**Speculative Execution**  
**Speculative Execution in Processors**

Sometimes bottlenecks are mitigated by executing the work that most likely follows them: we “speculatively execute” work that will probably, but not necessarily, come after our bottleneck.

For example, rather than waiting for the result of a conditional to be available in order to determine which branch to execute, the processor could simply proceed with the “most likely” branch, based on compile-time hints or runtime statistics. This particular technique for speculative execution is called “branch prediction”.

This can lead to large speedups when a particular branch of a conditional is taken only rarely (e.g. unhappy/error-handling paths) and requires a lot of work to execute (e.g. is subject to cache misses).

Speculative execution is infamous thanks to the Spectre vulnerability, which manipulates runtime statistics to “trick” the processor into executing out-of-bounds memory reads.

Undaunted by that cautionary tale of a multi-billion-dollar vulnerability, let’s consider how we might replicate this pattern of executing cheap but possibly wrong operations to speed up LLM inference.

**Speculative Execution in LLMs:**  
**Accelerating Large Language Model Decoding with Speculative Sampling and Fast Inference from Transformers via Speculative Decoding**

Two roughly-simultaneous papers from Google Research and DeepMind, perennial frenemies, demonstrated roughly-identical methods for large speedups in LLM generation by using cheaper models to predict certain tokens without changing the system’s output probabilities. In essence, speculatively generating a number of likely output tokens before the actual LLM is used to compute the final outputs.

The intuition behind speculative sampling is that some of the tokens in the output are very easy to guess – a period will come at the end of this sentence, for example – and so can be predicted very cheaply.

These methods further take advantage of the fact that computing the logprobs for a prompt + K tokens can be done in parallel. That makes it much cheaper than sampling K tokens to follow a prompt, which must be done serially – a painful and unavoidable fact of autoregressive models like Transformers or RNNs.

The K tokens following the prompt are generated by some cheap strategy – a smaller language model or even a heuristic rule. We then compute the logprobs for the prompt + K tokens in the large model, in parallel, and then throw out only those tokens that are improbable according to the large model.

Importantly, we reject samples in direct proportion to how improbable the large model thinks they are, so the combined system has the exact same output behavior as the original large model, but generally runs faster. This is a classic trick, rejection sampling, that goes back to the very first (analog!) computers in the 1940s.

For temperature 0, aka deterministic sampling, this equates to throwing out all tokens that follow the first wrong token put out by the speculative process.

The basic flow is captured well in this animation of speculative sampling from an excellent explainer by Joao Gante of Hugging Face:

![Speculative Sampling Animation](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

As with branch prediction, we do some work that might be wasted: running the draft/speculative model and scoring logprobs on all K tokens.

But because running the model on the prompt + K tokens is roughly the same cost as executing on the prompt + 1 token, for small K, we almost always come out ahead – much as branch predicting speculative execution comes out ahead because reading from memory and then executing the right branch is roughly the same cost as executing a wrong branch while reading from memory and then executing the right branch.

When used in a hierarchical configuration – regexes speculating for BERTs that speculate for GPTs – speculative sampling can achieve 2x speedups or greater.

Note that 2-3x is the typical cost difference between prompt tokens and output tokens in LLM APIs, and so well-executed speculative decoding can reduce that cost difference to almost nothing (thanks to Moin Nadeem of Replicate for thoughtful discussions on this).

**Registers**  
**Registers in Processors**

Programs generally achieve their effects on the world by writing information to memory visible to other processes or hardware – RAM or disk for other processes, VRAM for the display, network sockets for other computers, etc. Registers store small amounts of intermediate data during the computation of this information.

Unlike stack-allocated or heap-allocated memory, these values are stored in the processor itself and are essentially inaccessible to the programmer (without assembly-level backdoors) in high-level languages like C.

Because they are abstracted away from the programmer, they can be manipulated – e.g. by a compiler when optimizing the program – without concern for the side effects of those manipulations.

How might this pattern show up in LLMs?

**Registers in Large Transformer Models:**  
**Vision Transformers Need Registers**

Alright, this is cheating a bit, because it’s Vision Transformers, rather than Transformer language models, but it’s still a cool paper so I’m going to explain it.

There’s also a weaker but similar result for LLMs, based on “pause tokens”.

This paper claims that

- Vision Transformers use uninformative pixels as dynamic registers for storing intermediate information
- You can intentionally add empty “register tokens” to the input to remove this behavior

The first point is backed up by this gorgeous figure:

![Vision Transformers Registers](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

The bright colors indicate areas of the image to which the models attended when producing their predictions. Notably, large ViTs attend heavily to uninformative, background pixels.

Does this mean the models are learning to use artifacts of the dataset or adversarially-attackable side channel information to make their predictions?

Not necessarily!

Because each layer interacts additively with its inputs – the output of a layer with input x can be written as f(x) + x – Transformer layers can treat their inputs like a content-addressable memory, reading information written by earlier layers and writing in some of their own. For more on this view of Transformer internals, see the excellent work from Anthropic’s interpretability team.

It’s a neat way to do computation, but it has a big issue: if you want to write information that’s not tied to a specific token position, you don’t have a good place to put it.

It is hypothesized in the paper that large ViTs learn to use the least-informative token areas as a kind of scratchpad – like stealing a block of memory, using it to store intermediate values, and hoping you don’t break anything.

The paper proposes adding some blank “register” tokens to the input in order to give the model a safe spot to store the results of calculations that don’t otherwise have a place to go.

The addition of registers does not meaningfully improve performance on benchmarks (cf. Table 2 in the paper), but the resulting attention maps are much cleaner, as is obvious from the figure above, and so one might expect some downstream benefits, e.g. to interpretability or steerability.

**Paged Memory**  
**Paged Memory in Processors**

Memory must be allocated, and those allocations must be tracked and managed, e.g. defragmented, to maximize utilization of memory resources, which were precious even before the Chrome Nation attacked.

Memory allocators must handle a gnar trade-off: address-wise allocations make efficient use of memory in the best case, but lead to fragmentation and expensive allocator operations in reality, while large per-process/thread allocations are easy to manage but lead to wasted memory in the generic case that the allocations are not fully utilized. This particular form of under-utilization is called “internal fragmentation”.

The solution is to split the difference and allocate memory in multiples of moderately-sized blocks called “pages”.

The diagram below, from the BlogOS series by phil-opp, depicts the difference between fixed-size block allocation (left) and paged allocation (right). Notice that the allocation for the process in blue fails in the block allocation case but succeeds with pages:

![Paged Memory](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

Pages can be assigned to processes, loaded into caches, and otherwise managed as bulk units, while still being small enough (4 KB by default in most Linuxes) to be efficiently utilized.

LLMs are memory intensive, so might we be able to improve their performance by designing a better allocator?

**Paged Memory in LLMs:**  
**Efficient Memory Management for Large Language Model Serving with PagedAttention**

The focus of memory management in LLM inference is on the key-value (“KV”) cache, used to store the intermediate values of attention computations, for re-use when computing the outputs for future tokens in the sequence. This cache, introduced by the 2022 paper Efficiently Scaling Tansformer Inference from Google, converts a quadratic-time operation (compute attention for all token pairs in the sequence) into a linear-time one (compute only attention for the newest token in the sequence), at a linear cost in space (store keys and values for each token in the sequence).

If hot-swappable LoRA adapters ever take off, a similar amount of memory legerdemain will be required for the weights as well.

The KV cache is typically allocated as a single large block of memory, which is subject to the same issues as large block allocations in general.

This problem is especially acute for batched requests to LLM services. Because requests from different clients have varying prompt lengths and varying response lengths that are not known until run time, the utilization of the KV cache becomes highly uneven.

The situation is depicted nicely in this figure from the paper that introduced PagedAttention and the vLLM inference server that uses it. Note that the “internal fragmentation” sections should be several hundred times larger than they are depicted here:

![Paged Memory in LLMs](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

The solution proposed by the paper is to allocate the KV cache via pages – each one with enough space to hold a handful of KV states – and use a page table, much like the one in a processor, to map the logical memory of the cache to its physical address.

Like this:

![Paged Memory Mapping](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

The vLLM inference server that uses this technique is much faster than peer systems and allocates far less memory to serve the same workloads.

**Virtual Memory**  
**Virtual Memory in Processors**

In the beforetimes, when metal was metal, programmers stored information at addresses with names like 0x0BFF and they really meant it.

They could expect that if they took their trusty oscilloscope to the 3,071st/0x0BFFth memory cell of their spacious 64KB of RAM, they would find humming electrons vibing to the pattern they had stored.

This has an obvious problem: if two 00s tween programmers attempt to use the one and only 0x0BFF address to store program data at the same time, someone’s data will be overwritten or read improperly – akin to the problems of addressing more than one person as your BFF.

Larger address spaces allow for the definition of additional BFFs, e.g. 0x0BFFAEAE in 32 bit address spaces, but this only reduces the chance of collision without eliminating it.

The solution is to use a virtual memory system: programmers and their programs are presented with a gorgeous row of linear addresses, from 0x00000000 to 0xFFFFFFFF (or whatever the highest address is), and the operating system and hardware map those addresses to physical memory.

This indirection is also useful for pages! Instead of mapping individual addresses, virtual memory maps typically operate at the page level.

Virtual memory’s indirection allows a process to address much more than the available RAM – for example virtual memory addresses can be mapped to locations on disk or on somebody else’s computer.

RAM is limited and expensive, relative to disk, so being able to use disk as memory is a big win.

Language models also have memory limits: when producing tokens, they can only refer to at most a fixed number of previous context tokens.

Hard limits on token count have rapidly increased from the few thousands to the few hundreds of thousands. But models struggle to effectively make use of those long contexts.

How might we apply the pattern of virtual memory to LLMs to also allow them to effectively access much larger storage?

**Virtual Memory in LLMs:**  
**MemGPT: Towards LLMs as Operating Systems**

The MemGPT pattern uses prompting and careful design of tools to give LLMs the ability to manage their context – analogically treating the context as the physical memory and all of the rest of the addressable information as virtual memory.

The pattern is depicted in this figure from the paper:

![MemGPT Virtual Memory](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

As in retrieval-augmented generation (RAG) patterns, the addressable information is stored outside the LLM and interfaced with by traditional software. That means it can be a database, a filesystem, or any other form of storage.

But unlike typical RAG, in MemGPT retrieval from the external context is done by the LLM, via function-calling tool use, rather than being hard-coded. This style is associated more with agent patterns and is used in the OpenAI Assistants API.

The LLM is prompted to retrieve the information it needs and then add it to its prompt – much like virtual memory stored on disk can be paged into RAM.

Even further down the path to agency and away from simple RAG, in the MemGPT pattern the LLM is also responsible for writing information that overflows the context window back to the storage system. This pattern was popularized by the Generative Agents paper, which uses LLMs to drive video game NPCs. There, agents had the ability to “reflect” on their experiences and write those reflections into their memory.

**What Next: LLMs as kernels?**  
A speculative diagram for an “LLM OS” by @karpathy.

A key novelty of the MemGPT approach, relative to other similar systems, is the event-driven style: the LLM sits idle, waiting for events like user messages, timer ticks, or state changes in the world.

This is an extremely common pattern in the systems discipline – on every keystroke, button press, or filesystem change, a typical operating system interrupts running processes to respond to the event, e.g. to pass the keystroke to the process managing the active window. Browsers are similarly event-driven.

Interruptibility and event-driven-ness are key features of biological agents as well. To quote Copilot’s suggested completion of this paragraph: “If you poke a cat, it will stop what it’s doing and respond to the poke.”

When that suggestion appeared (an event) it stopped me from writing (interrupted my writing process). I was triggered to reflect on it (I handled the interrupt by updating my state). I then went back to writing (resumed my writing process) with a new idea for what to say next.

It is clear that if LLMs are to become the cognitive kernels of agents in any way worthy of the name, they will need a similar architecture.

So while drawing architectures from the computational cognitive science literature is a good idea, we as MLRs should take care to draw from the work on engineering operating systems, browsers, database engines, and other systems as well."

**URL:** [Read More](https://charlesfrye.github.io/programming/2023/11/10/llms-systems.html)

#### Suggested labels
#### </details>

### #161: Exllama isn't 100% deterministic.
<details><summary>### Details</summary>Similarity score: 0.81
              Short answer: The results you're getting are expected because the implementation isn't 100% deterministic.

Now, please forgive the following rant, but since this question comes up often I may as well explain it in detail so I have something to refer to next time.

What it comes down to is the use of atomic operations in the GEMV-oriented matmul kernels, the fact that CUDA's thread launch order is nondeterministic and the fact that floating-point addition is non-associative. Essentially (a+b)+c != a+(b+c) for floating point types, and if you compute a+b+c across threads in CUDA using atomic addition, you can't know if the result is going to be (a+b)+c or a+(b+c). The two results are often the same but they can sometimes differ by a tiny amount due to rounding of the intermediate result.

Now, after accumulating millions and millions of those tiny errors, one forward pass might produce a distribution of [0.700, 0.104, 0.102...] while the same forward pass next time around could give you [0.702, 0.101, 0.100...]. Both would be correct *to the precision of FP16*, but they wouldn't be identical bit-for-bit.

Then, all you need is one binomial sample that's right on the boundary between two tokens, say, sampling to a cutoff of 0.701 in that example, and your output sequences are now different and diverging. Or you could end up with distributions where the top two tokens are practically the same probability, and the random jitter flips their order, so even greedy sampling can give diverging results. This seems likely in your example since the divergence starts at the point of `Artificial intelligence (AI) is` followed by either ` a` or ` the`, both of which seem like they would be highly preferred tokens, quite possibly scoring roughly the same and becoming a "tipping point" in the autoregressive sequence.

As for what to do about it, well, you can either do inference in FP32 while rounding to FP16 at deterministic points along the way, hoping that the FP32 error never accumulates to the point that it would flip a bit in the nearest FP16 value, or you can use deterministic (reduction-based) matmul approaches. Both of those hurt performance, so there's no immediate support for them in ExLlama. 

The third option is to question the need for determinism in the first place. Consider this:

- If you're already using quantized models it's clearly not perfect precision you're after. The problem with nondeterminism can't be that it doesn't give you "the precisely correct result" because that went out the window anyway when you distilled the model down to the most important 25% of its bits.

- If you get two slightly different outputs from the same input, there's no sense in which either of the two outputs is the correct one, unless you arbitrarily *define* an order of additions to be canonical and then write/select CUDA kernels to always follow that order. But then the resulting output is still only correct by an arbitrary definition which depends on specifics you're probably not concerned with, such as which kernel (or set of kernels) you end up launching by calling `torch.matmul()` in Python or `cublasHgemm` in C++. It can even change with your CUDA version or your hardware architecture. From the cuBLAS API docs:

>By design, all cuBLAS API routines from a given toolkit version, generate the same bit-wise results at every run when executed on GPUs with the same architecture and the same number of SMs. However, bit-wise reproducibility is not guaranteed across toolkit versions because the implementation might differ due to some implementation changes.

- What is it that you *actually* achieve by passing the same input twice instead of just duplicating the output? Consider if the implementation secretly did this to "fake" being deterministic, i.e., imagine it cached the result of each forward pass using a database of hashed inputs and whatever was the first output non-deterministically computed for each of them. Is there any conceivable way you could detect that the determinism was "faked" in this way, if you just had the outputs to go by?

Personally, I would argue that good testing methodologies in this context need to be robust to noise anyway. Yes, bitwise-identical outputs are a useful proxy for functionally identical implementations, as a way to quickly verify that you didn't make any subtle mistakes by having a huge, chaotic-dynamic computation arrive at the exact same result as a reference implementation.

But it doesn't tell you anything more than that. As soon as you switch to a different GPU, or you split your tensors across multiple GPUs, or you update to a new version of PyTorch, your could get any *other* output from the set of possible outputs that are *all* correct to within the precision of FP16. If you're getting `Artificial intelligence (AI) is the field of study...` on your system, a user of whatever application you're building might still see `Artificial intelligence (AI) is a field of computer science...` with the exact same prompt, *only* because they're two weeks behind on nightly builds of PyTorch.

And even within a single, deterministic context, causal LM is still causal which makes it is chaotic and sensitive to minute changes in initial conditions: Try the same sequence with an extra space at the beginning and watch it take a completely different turn regardless of precision and determinism in the underlying framework.

All in all, while it would be nice to add determinism as an option, it would either degrade performance just for the sake of test cases like yours, or it would be a switchable option that doesn't actually prove anything about the correctness of the other, non-deterministic code path.

Again, sorry for the rant. But since your observation is correct and your concern is entirely valid I feel it deserves a full explanation. I'd happily entertain discussion if anyone should disagree.

_Originally posted by @turboderp in https://github.com/turboderp/exllamav2/issues/232#issuecomment-1860896496_
            </details>

### #654: Representation engineering:
<details><summary>### Details</summary>Similarity score: 0.81
- [ ] [I'm the author of the GPT-2 work. This is a nice post, thanks for making it more... | Hacker News](https://news.ycombinator.com/item?id=39436215)


# TITLE
I'm the author of the GPT-2 work. This is a nice post, thanks for making it more... | Hacker News

# DESCRIPTION
"urn_Trout 8 days ago | parent | context | flag | favorite | on: Representation Engineering: Mistral-7B on Acid

I'm the author of the GPT-2 work. This is a nice post, thanks for making it more available. :)
Li et al[1] and I independently derived this technique last spring, and also someone else independently derived it last fall. Something is in the air.
Regarding your footnote 2 re capabilities: I considered these kinds of uses before releasing the technique. Ultimately, practically successful real-world alignment techniques will let you do new things (which is generally good IMO). The technique so far seems to be delivering the new things I was hoping for.
[1] [https://openreview.net/forum?id=aLLuYpn83y](https://openreview.net/forum?id=aLLuYpn83y)"

# URL
[https://news.ycombinator.com/item?id=39436215](https://news.ycombinator.com/item?id=39436215)

#### Suggested labels
#### {'label-name': 'Technological Advancements', 'label-description': 'Topics related to cutting-edge advancements in technology and AI techniques.', 'confidence': 54.52}</details>

### #641: Guide to choosing quants and engines : r/LocalLLaMA
<details><summary>### Details</summary>Similarity score: 0.81
- [ ] [Guide to choosing quants and engines : r/LocalLLaMA](https://www.reddit.com/r/LocalLLaMA/comments/1anb2fz/comment/kprbduc/)


# Guide to choosing quants and engines : r/LocalLLaMA

**DESCRIPTION:**  
Ever wonder which type of quant to download for the same model, GPTQ or GGUF or exl2? And what app/runtime/inference engine you should use for this quant? Here's my guide.

**TLDR:**

- If you have multiple gpus of the same type (3090x2, not 3090+3060), and the model can fit in your vram: Choose AWQ+Aphrodite (4 bit only) > GPTQ+Aphrodite > GGUF+Aphrodite;
- If you have a single gpu and the model can fit in your vram, or multiple gpus with different vram sizes: Choose exl2+exllamav2 ≈ GPTQ+exllamav2 (4 bit only);
- If you need to do offloading or your gpu does not support Aprodite/exllamav2, GGUF+llama.cpp is your only choice.

You want to use a model but cannot fit it in your vram in fp16, so you have to use quantization. When talking about quantization, there are two concept, First is the format, how the model is quantized, the math behind the method to compress the model in a lossy way; Second is the engine, how to run such a quantized model. Generally speaking, quantization of the same format at the same bitrate should have the exactly same quality, but when run on different engines the speed and memory consumption can differ dramatically.

Please note that I primarily use 4-8 bit quants on Linux and never go below 4, so my take on extremely tight quants of <=3 bit might be completely off.

**Part I: review of quantization formats.**

There are currently 4 most popular quant formats:

- GPTQ: The old and good one. It is the first "smart" quantization method. It ultilizes a calibration dataset to improve quality at the same bitrate. Takes a lot time and vram+ram to make a GPTQ quant. Usually comes at 3, 4, or 8 bits. It is widely adapted to almost all kinds of model and can be run on may engines.
- AWQ: An even "smarter" format than GPTQ. In theory it delivers better quality than GPTQ of the same bitrate. Usually comes at 4 bits. The recommended quantization format by vLLM and other mass serving engines.
- GGUF: A simple quant format that doesn't require calibration, so it's basically round-to-nearest argumented with grouping. Fast and easy to quant but not the "smart" type. Recently imatrix was added to GGUF, which also ultilizes a calibration dataset to make it smarter like GPTQ. GGUFs with imatrix ususally has the "IQ" in name: like "name-IQ3_XS" vs the original "name-Q3_XS". However imatrix is usually applied to tight quants <= 3 and I don't see many larger GGUF quants made with imatrix.
- EXL2: The quantization format used by exllamav2. EXL2 is based on the same optimization method as GPTQ. The major advantage of exl2 is that it allows mixing quantization levels within a model to achieve any average bitrate between 2 and 8 bits per weight. So you can tailor the bitrate to your vram: You can fit a 34B model in a single 4090 in 4.65 bpw at 4k context, improving a bit of quality over 4 bit. But if you want longer ctx you can lower the bpw to 4.35 or even 3.5.

So in terms of quality of the same bitrate, AWQ > GPTQ = EXL2 > GGUF. I don't know where should GGUF imatrix be put, I suppose it's at the same level as GPTQ.

Besides, the choice of calibration dataset has subtle effect on the quality of quants. Quants at lower bitrates have the tendency to overfit on the style of the calibration dataset. Early GPTQs used wikitext, making them slightly more "formal, dispassionate, machine-like". The default calibration dataset of exl2 is carefully picked by its author to contain a broad mix of different types of data. There are often also "-rpcal" flavours of exl2 calibrated on roleplay datasets to enhance RP experience.

**Part II: review of runtime engines.**

Different engines support different formats. I tried to make a table:

Comparison of quant formats and engines
Pre-allocation: The engine pre-allocate the vram needed by activation and kv cache, effectively reducing vram usage and improving speed because pytorch handles vram allocation badly. However, pre-allocation means the engine need to take as much vram as your model's max ctx length requires at the start, even if you are not using it.

VRAM optimization: Efficient attention implementation like FlashAttention or PagedAttention to reduce memory usage, especially at long context.

One notable player here is the Aphrodite-engine ([Aphrodite-engine](https://github.com/PygmalionAI/aphrodite-engine)). At first glance it looks like a replica of vLLM, which sounds less attractive for in-home usage when there are no concurrent requests. However after GGUF is supported and exl2 on the way, it could be a game changer. It supports tensor-parallel out of the box, that means if you have 2 or more gpus, you can run your (even quantized) model in parallel, and that is much faster than all the other engines where you can only use your gpus sequentially. I achieved 3x speed over llama.cpp running miqu using 4 2080 Ti!

**Some personal notes:**

- If you are loading a 4 bit GPTQ model in hugginface transformer or AutoGPTQ, unless you specify otherwise, you will be using the exllama kernel, but not the other optimizations from exllama.
- 4 bit GPTQ over exllamav2 is the single fastest method without tensor parallel, even slightly faster than exl2 4.0bpw.
- vLLM only supports 4 bit GPTQ but Aphrodite supports 2,3,4,8 bit GPTQ.
- Lacking FlashAttention at the moment, llama.cpp is inefficient with prompt preprocessing when context is large, often taking several seconds or even minutes before it can start generation. The actual generation speed is not bad compared to exllamav2.
- Even with one gpu, GGUF over Aphrodite can ultilize PagedAttention, possibly offering faster preprocessing speed than llama.cpp.

**Update:** shing3232 kindly pointed out that you can convert a AWQ model to GGUF and run it in llama.cpp. I never tried that so I cannot comment on the effectiveness of this approach.

**URL:** [Guide to choosing quants and engines](https://www.reddit.com/r/LocalLLaMA/comments/1anb2fz/comment/kprbduc/)

#### Suggested labels
#### {'label-name': 'model-quantization-guide', 'label-description': 'Information on choosing quantization formats for machine learning models.', 'confidence': 65.61}</details>

### #639: The Querynomicon: An Introduction to SQL for Weary Data Scientists
<details><summary>### Details</summary>Similarity score: 0.8
- [ ] [The Querynomicon](https://gvwilson.github.io/sql-tutorial/)


# The Querynomicon

**DESCRIPTION:** "The Querynomicon

An Introduction to SQL for Weary Data Scientists

Upon first encountering SQL after two decades of Fortran, C, Java, and Python, I thought I had stumbled into hell. I quickly realized that was optimistic: after all, hell has rules.

I have since realized that SQL does too, and that they are no more confusing or contradictory than those of most other programming languages. They only appear so because it draws on a tradition unfamiliar to those of us raised with derivatives of C. To quote Terry Pratchett, it is not mad, just differently sane.

Welcome, then, to a world in which the strange will become familiar, and the familiar, strange. Welcome, thrice welcome, to SQL.

"The Querynomicon" is a Third Bit production.

**What This Is**

- Notes and working examples that instructors can use to perform a lesson
- Do not expect novices with no prior SQL experience to be able to learn from them
- Musical analogy
- This is the chord changes and melody
- We expect instructors to create an arrangement and/or improvise while delivering
- See Teaching Tech Together for background
- Please see the license for terms of use, the Code of Conduct for community standards, and these guidelines for contributing
- Greg Wilson is a programmer, author, and educator based in Toronto

**Scope**

- **intended audience**
  - Rachel has a master’s degree in cell biology and now works in a research hospital doing cell assays.
  - She learned a bit of R in an undergrad biostatistics course and has been through the Carpentries lesson on the Unix shell.
  - Rachel is thinking about becoming a data scientist and would like to understand how data is stored and managed.
  - Her work schedule is unpredictable and highly variable, so she needs to be able to learn a bit at a time.
- **prerequisites**
  - basic Unix command line: cd, ls, * wildcard
  - basic tabular data analysis: filtering rows, aggregating within groups
- **learning outcomes**
  - Explain the difference between a database and a database manager.
  - Write SQL to select, filter, sort, group, and aggregate data.
  - Define tables and insert, update, and delete records.
  - Describe different types of join and write queries that use them to combine data.
  - Use windowing functions to operate on adjacent rows.
  - Explain what transactions are and write queries that roll back when constraints are violated.
  - Explain what triggers are and write SQL to create them.
  - Manipulate JSON data using SQL.
  - Interact with a database using Python directly, from a Jupyter notebook, and via an ORM."

**URL:** [The Querynomicon](https://gvwilson.github.io/sql-tutorial/)

#### Suggested labels
#### {'label-name': 'SQL-introduction', 'label-description': 'Introduction to SQL for beginners and data scientists', 'gh-repo': 'https://github.com/gvwilson/sql-tutorial', 'confidence': 78.55}</details>

### #545: Pragma statements supported by SQLite
<details><summary>### Details</summary>Similarity score: 0.8
- [ ] [https://sqlite.org/pragma.html](https://sqlite.org/pragma.html#toc)


# Pragma statements supported by SQLite

## Description
The PRAGMA statement is an SQL extension specific to SQLite and used to modify the operation of the SQLite library or to query the SQLite library for internal (non-table) data. The PRAGMA statement is issued using the same interface as other SQLite commands (e.g. SELECT, INSERT) but is different in the following important respects:

- The pragma command is specific to SQLite and is not compatible with any other SQL database engine.
- Specific pragma statements may be removed and others added in future releases of SQLite. There is no guarantee of backwards compatibility.
- No error messages are generated if an unknown pragma is issued. Unknown pragmas are simply ignored. This means if there is a typo in a pragma statement the library does not inform the user of the fact.
- Some pragmas take effect during the SQL compilation stage, not the execution stage. This means if using the C-language sqlite3_prepare(), sqlite3_step(), sqlite3_finalize() API (or similar in a wrapper interface), the pragma may run during the sqlite3_prepare() call, not during the sqlite3_step() call as normal SQL statements do. Or the pragma might run during sqlite3_step() just like normal SQL statements. Whether or not the pragma runs during sqlite3_prepare() or sqlite3_step() depends on the pragma and on the specific release of SQLite.
- The EXPLAIN and EXPLAIN QUERY PLAN prefixes to SQL statements only affect the behavior of the statement during sqlite3_step(). That means that PRAGMA statements that take effect during sqlite3_prepare() will behave the same way regardless of whether or not they are prefaced by "EXPLAIN".
- The C-language API for SQLite provides the SQLITE_FCNTL_PRAGMA file control which gives VFS implementations the opportunity to add new PRAGMA statements or to override the meaning of built-in PRAGMA statements.

## PRAGMA Command Syntax
```sql
PRAGMA schema-name.pragma-name(pragma-value) = pragma-value
```

- A pragma can take either zero or one argument. The argument is may be either in parentheses or it may be separated from the pragma name by an equal sign. The two syntaxes yield identical results. In many pragmas, the argument is a boolean. The boolean can be one of:
  - 1, yes, true, on
  - 0, no, false, off

- Keyword arguments can optionally appear in quotes. (Example: 'yes' [FALSE].) Some pragmas takes a string literal as their argument. When pragma takes a keyword argument, it will usually also take a numeric equivalent as well. For example, "0" and "no" mean the same thing, as does "1" and "yes". When querying the value of a setting, many pragmas return the number rather than the keyword.

- A pragma may have an optional schema-name before the pragma name. The schema-name is the name of an ATTACH-ed database or "main" or "temp" for the main and the TEMP databases. If the optional schema name is omitted, "main" is assumed. In some pragmas, the schema name is meaningless and is simply ignored. In the documentation below, pragmas for which the schema name is meaningful are shown with a "schema." prefix.

## PRAGMA Functions
PRAGMAs that return results and that have no side-effects can be accessed from ordinary SELECT statements as table-valued functions. For each participating PRAGMA, the corresponding table-valued function has the same name as the PRAGMA with a 7-character "pragma_" prefix. The PRAGMA argument and schema, if any, are passed as arguments to the table-valued function, with the schema as an optional, last argument.

For example, information about the columns in an index can be read using the index_info pragma as follows:
```sql
PRAGMA index_info('idx52');
```
Or, the same content can be read using:
```sql
SELECT * FROM pragma_index_info('idx52');
```

The advantage of the table-valued function format is that the query can return just a subset of the PRAGMA columns, can include a WHERE clause, can use aggregate functions, and the table-valued function can be just one of several data sources in a join. For example, to get a list of all indexed columns in a schema, one could query:
```sql
SELECT DISTINCT m.name || '.' || ii.name AS 'indexed-columns'
  FROM sqlite_schema AS m,
       pragma_index_list(m.name) AS il,
       pragma_index_info(il.name) AS ii
 WHERE m.type='table'
 ORDER BY 1;
```

Additional notes:
- Table-valued functions exist only for built-in PRAGMAs, not for PRAGMAs defined using the SQLITE_FCNTL_PRAGMA file control.
- Table-valued functions exist only for PRAGMAs that return results and that have no side-effects.
- This feature could be used to implement information schema by first creating a separate schema using
```sql
ATTACH ':memory:' AS 'information_schema';
```
Then creating VIEWs in that schema that implement the official information schema tables using table-valued PRAGMA functions.

The table-valued functions for PRAGMA feature was added in SQLite version 3.16.0 (2017-01-02). Prior versions of SQLite cannot use this feature.

[More information](https://sqlite.org/pragma.html#toc)

#### Suggested labels
#### {'label-name': 'SQL commands', 'label-description': 'Descriptions and syntax of SQL commands specific to SQLite.', 'confidence': 66.84}</details>
