### ISSUE TITLE
static-wiki/src/sqlite.js at b0ae18ed02ca64263075c3516c38a504f46e10c4 · segfall/static-wiki

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#692]
- [ ] [static-wiki/src/sqlite.js at b0ae18ed02ca64263075c3516c38a504f46e10c4 · segfall/static-wiki](https://github.com/segfall/static-wiki/blob/b0ae18ed02ca64263075c3516c38a504f46e10c4/src/sqlite.js#L2)

# TITLE: static-wiki/src/sqlite.js at b0ae18ed02ca64263075c3516c38a504f46e10c4 · segfall/static-wiki

**DESCRIPTION:**
```javascript
import { createDbWorker } from "sql.js-httpvfs"
import db from "../db.js";

export default async function (key='en') {
    // sadly there's no good way to package workers and wasm directly so you need a way to get these two URLs from your bundler.
    // This is the webpack5 way to create a asset bundle of the worker and wasm:
    const workerUrl = new URL(
        "/sqlite.worker.js",
        window.location.origin,
    );
    const wasmUrl = new URL(
        "/sql-wasm.wasm",
        window.location.origin,
    );
    // the legacy webpack4 way is something like `import wasmUrl from "file-loader!sql.js-httpvfs/dist/sql-wasm.wasm"`.
    // the config is either the url to the create_db script, or a inline configuration:
    const config = {
        from: "inline",
        config: {
            serverMode: "full", // file is just a plain old full sqlite database
            requestChunkSize: 8192, // the page size of the  sqlite database (by default 4096)
            url: window.location.origin.includes("localhost") ? db[key].dev : db[key].production // url to the database (relative or full)
        }
    }

    const worker = await createDbWorker(
        [config],
        workerUrl.toString(), wasmUrl.toString()
    );
    // you can also pass multiple config objects which can then be used as separate database schemas with `ATTACH virtualFilename as schemaname`, where virtualFilename is also set in the config object.
    // worker.db is a now SQL.js instance except that all functions return Promises.

    return worker;
}
```

**URL:** [Link to the code](https://github.com/segfall/static-wiki/blob/b0ae18ed02ca64263075c3516c38a504f46e10c4/src/sqlite.js#L2)

#### {'label-name': 'web-development', 'label-description': 'Includes code libraries and tools for developing web applications.', 'confidence': 77.7}

**Comment by irthomasthomas** [comment]
### Related content
### #74: Sqlite WASM and Github Pages
<details><summary>### Details</summary>Similarity score: 0.92
- [ ] [merge sqlite - Kagi Search](https://kagi.com/search?q=merge+sqlite&from_date=2021-01-01)
- [ ] [sql - Fastest Way merge two SQLITE Databases - Stack Overflow](https://stackoverflow.com/questions/9349659/fastest-way-merge-two-sqlite-databases)
- [ ] [simonw/sqlite-utils: Python CLI utility and library for manipulating SQLite databases](https://github.com/simonw/sqlite-utils)
- [ ] [sqlite-utils](https://sqlite-utils.datasette.io/en/stable/)
- [ ] [GitHub Pages | Websites for you and your projects, hosted directly from your GitHub repository. Just edit, push, and your changes are live.](https://pages.github.com/)
- [ ] [sqlite wasm sql.js github pages - Kagi Search](https://kagi.com/search?q=sqlite+wasm+sql.js+github+pages)
- [ ] [phiresky/sql.js-httpvfs: Hosting read-only SQLite databases on static file hosters like Github Pages](https://github.com/phiresky/sql.js-httpvfs)
- [ ] [sqlite3 WebAssembly & JavaScript Documentation Index](https://sqlite.org/wasm/doc/trunk/index.md)
- [ ] [phiresky/youtube-sponsorship-stats/](https://github.com/phiresky/youtube-sponsorship-stats/)
- [ ] [phiresky/world-development-indicators-sqlite/](https://github.com/phiresky/world-development-indicators-sqlite/)
- [ ] [Show HN: Fully-searchable Library Genesis on IPFS | Hacker News](https://news.ycombinator.com/item?id=28585208)
- [ ] [nalgeon/sqlime: Online SQLite playground](https://github.com/nalgeon/sqlime)
- [ ] [nalgeon/sqlean.js: Browser-based SQLite with extensions](https://github.com/nalgeon/sqlean.js)
- [ ] [Sqlime - SQLite Playground](https://sqlime.org/)
- [ ] [sqlite-wasm-http - npm](https://www.npmjs.com/package/sqlite-wasm-http)
- [ ] [Postgres WASM by Snaplet and Supabase](https://supabase.com/blog/postgres-wasm)
- [ ] [rhashimoto/wa-sqlite: WebAssembly SQLite with experimental support for browser storage extensions](https://github.com/rhashimoto/wa-sqlite)
- [ ] [jlongster/absurd-sql: sqlite3 in ur indexeddb (hopefully a better backend soon)](https://github.com/jlongster/absurd-sql)
- [ ] [help: basic example for the web browser · Issue #23 · phiresky/sql.js-httpvfs](https://github.com/phiresky/sql.js-httpvfs/issues/23)
- [ ] [phiresky/sql.js-httpvfs: Hosting read-only SQLite databases on static file hosters like Github Pages](https://github.com/phiresky/sql.js-httpvfs#minimal-example-from-scratch)
- [ ] [sql.js-httpvfs/example at master · phiresky/sql.js-httpvfs](https://github.com/phiresky/sql.js-httpvfs/tree/master/example)
- [ ] [Code search results](https://github.com/search?utf8=%E2%9C%93&q=sql.js-httpvfs&type=code)
- [ ] [knowledge/docs/databases/sqlite.md at 7c4bbc755c64368a82ca22b76566e9153cd2e377 · nikitavoloboev/knowledge](https://github.com/nikitavoloboev/knowledge/blob/7c4bbc755c64368a82ca22b76566e9153cd2e377/docs/databases/sqlite.md?plain=1#L96)
- [ ] [static-wiki/src/sqlite.js at b0ae18ed02ca64263075c3516c38a504f46e10c4 · segfall/static-wiki](https://github.com/segfall/static-wiki/blob/b0ae18ed02ca64263075c3516c38a504f46e10c4/src/sqlite.js#L2)
</details>

### #691: gh actions sqlite wasm
<details><summary>### Details</summary>Similarity score: 0.91
- [ ] [gh actions sqlite wasm](https://github.com/ilmalte/github-actions-with-sqlite/blob/36f835a5a66873f460d4025e2d3f22bf4bacbcc1/ui/index.html#L3)

# Title: gh actions sqlite wasm

## Description:
```html
<!DOCTYPE html>

<title>Minimal sql.js-httpvfs demo</title>
<!-- DEV: -->
<script src="./dist/bundle.js"></script>
<!-- PROD: -->
<!-- <script src="./bundle.js"></script> -->
<script>

    // Check if WebAssembly is supported for the target browser
    const supported = (() => {
        try {
            if (typeof WebAssembly === "object"
                && typeof WebAssembly.instantiate === "function") {
                const module = new WebAssembly.Module(Uint8Array.of(0x0, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00));
                if (module instanceof WebAssembly.Module)
                    return new WebAssembly.Instance(module) instanceof WebAssembly.Instance;
            }
        } catch (e) {
        }
        return false;
    })();
    console.log(supported ? "WebAssembly is supported" : "WebAssembly is not supported");


    // TODO: Dynamically load bundle.js based on env
    // var isProduction = process.env.NODE_ENV == 'production';
    // var src = isProduction ? "./bundle.js" : "./dist/bundle.js";
    // document.write('<script src="' + src + '"><\/script>');

</script>
<div>Hello World! If you don't see anything probably your browser doesn't support WebAssembly</div>
```

## URL:
[GitHub Repository](https://github.com/ilmalte/github-actions-with-sqlite/blob/36f835a5a66873f460d4025e2d3f22bf4bacbcc1/ui/index.html#L3)

#### Suggested labels
#### </details>

### #678: chroma/README.md at main · chroma-core/chroma
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [chroma/README.md at main · chroma-core/chroma](https://github.com/chroma-core/chroma/blob/main/README.md?plain=1)


# chroma/README.md at main · chroma-core/chroma

<p align="center">
  <a href="https://trychroma.com"><img src="https://user-images.githubusercontent.com/891664/227103090-6624bf7d-9524-4e05-9d2c-c28d5d451481.png" alt="Chroma logo"></a>
</p>

<p align="center">
    <b>Chroma - the open-source embedding database</b>. <br />
    The fastest way to build Python or JavaScript LLM apps with memory!
</p>

<p align="center">
  <a href="https://discord.gg/MMeYNTmh3x" target="_blank">
      <img src="https://img.shields.io/discord/1073293645303795742" alt="Discord">
  </a> |
  <a href="https://github.com/chroma-core/chroma/blob/master/LICENSE" target="_blank">
      <img src="https://img.shields.io/static/v1?label=license&message=Apache 2.0&color=white" alt="License">
  </a> |
  <a href="https://docs.trychroma.com/" target="_blank">
      Docs
  </a> |
  <a href="https://www.trychroma.com/" target="_blank">
      Homepage
  </a>
</p>


<p align="center">
  <a href="https://github.com/chroma-core/chroma/actions/workflows/chroma-integration-test.yml" target="_blank">
    <img src="https://github.com/chroma-core/chroma/actions/workflows/chroma-integration-test.yml/badge.svg?branch=main" alt="Integration Tests">
  </a> |
  <a href="https://github.com/chroma-core/chroma/actions/workflows/chroma-test.yml" target="_blank">
    <img src="https://github.com/chroma-core/chroma/actions/workflows/chroma-test.yml/badge.svg?branch=main" alt="Tests">
  </a>
</p>

```bash
pip install chromadb # python client
# for javascript, npm install chromadb!
# for client-server mode, chroma run --path /chroma_db_path
```

The core API is only 4 functions (run our [💡 Google Colab](https://colab.research.google.com/drive/1QEzFyqnoFxq7LUGyP1vzR4iLt9PpCDXv?usp=sharing) or [Replit template](https://replit.com/@swyx/BasicChromaStarter?v=1)):

```python
import chromadb
# setup Chroma in-memory, for easy prototyping. Can add persistence easily!
client = chromadb.Client()

# Create collection. get_collection, get_or_create_collection, delete_collection also available!
collection = client.create_collection("all-my-documents")

# Add docs to the collection. Can also update and delete. Row-based API coming soon!
collection.add(
    documents=["This is document1", "This is document2"], # we handle tokenization, embedding, and indexing automatically. You can skip that and add your own embeddings as well
    metadatas=[{"source": "notion"}, {"source": "google-docs"}], # filter on these!
    ids=["doc1", "doc2"], # unique for each doc
)

# Query/search 2 most similar results. You can also .get by id
results = collection.query(
    query_texts=["This is a query document"],
    n_results=2,
    # where={"metadata_field": "is_equal_to_this"}, # optional filter
    # where_document={"$contains":"search_string"}  # optional filter
)
```

## Features
- __Simple__: Fully-typed, fully-tested, fully-documented == happiness
- __Integrations__: [`🦜️🔗 LangChain`](https://blog.langchain.dev/langchain-chroma/) (python and js), [`🦙 LlamaIndex`](https://twitter.com/atroyn/status/1628557389762007040) and more soon
- __Dev, Test, Prod__: the same API that runs in your python notebook, scales to your cluster
- __Feature-rich__: Queries, filtering, density estimation and more
- __Free & Open Source__: Apache 2.0 Licensed

## Use case: ChatGPT for ______

For example, the `"Chat your data"` use case:
1. Add documents to your database. You can pass in your own embeddings, embedding function, or let Chroma embed them for you.
2. Query relevant documents with natural language.
3. Compose documents into the context window of an LLM like `GPT3` for additional summarization or analysis.

## Embeddings?

What are embeddings?

- [Read the guide from OpenAI](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings)
- __Literal__: Embedding something turns it from image/text/audio into a list of numbers. 🖼️ or 📄 => `[1.2, 2.1, ....]`. This process makes documents "understandable" to a machine learning model.
- __By analogy__: An embedding represents the essence of a document. This enables documents and queries with the same essence to be "near" each other and therefore easy to find.
- __Technical__: An embedding is the latent-space position of a document at a layer of a deep neural network. For models trained specifically to embed data, this is the last layer.
- __A small example__: If you search your photos for "famous bridge in San Francisco". By embedding this query and comparing it to the embeddings of your photos and their metadata - it should return photos of the Golden Gate Bridge.

Embeddings databases (also known as **vector databases**) store embeddings and allow you to search by nearest neighbors rather than by substrings like a traditional database. By default, Chroma uses [Sentence Transformers](https://docs.trychroma.com/embeddings#sentence-transformers) to embed for you but you can also use OpenAI embeddings, Cohere (multilingual) embeddings, or your own.

[View on GitHub](https://github.com/chroma-core/chroma/blob/main/README.md?plain=1)

#### Suggested labels
#### </details>

### #642: TabbyML: Self-hosted AI coding assistant.
<details><summary>### Details</summary>Similarity score: 0.83
- [ ] [tabby/README.md at main · TabbyML/tabby](https://github.com/TabbyML/tabby/blob/main/README.md?plain=1)

# tabby/README.md at main · TabbyML/tabby

<div align="center">

# 🐾 Tabby

[![latest release](https://shields.io/github/v/release/TabbyML/tabby?sort=semver)](https://github.com/TabbyML/tabby/releases/latest)
[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://makeapullrequest.com)
[![Docker pulls](https://img.shields.io/docker/pulls/tabbyml/tabby)](https://hub.docker.com/r/tabbyml/tabby)
[![codecov](https://codecov.io/gh/TabbyML/tabby/graph/badge.svg?token=WYVVH8MKK3)](https://codecov.io/gh/TabbyML/tabby)

</div>

Tabby is a self-hosted AI coding assistant, offering an open-source and on-premises alternative to GitHub Copilot. It boasts several key features:
* Self-contained, with no need for a DBMS or cloud service.
* OpenAPI interface, easy to integrate with existing infrastructure (e.g Cloud IDE).
* Supports consumer-grade GPUs.

<p align="center">
  <a target="_blank" href="https://tabbyml.github.io/tabby/playground"><img alt="Open in Playground" src="https://img.shields.io/badge/OPEN%20IN%20PLAYGROUND-blue?logo=xcode&style=for-the-badge&logoColor=green"></a>
</p>

<p align="center">
  <img alt="Demo" src="https://user-images.githubusercontent.com/388154/230440226-9bc01d05-9f57-478b-b04d-81184eba14ca.gif">
</p>

## 🔥 What's New

* **12/23/2023** Seamlessly [deploy Tabby on any cloud](https://tabby.tabbyml.com/docs/installation/skypilot/) with [SkyServe](https://skypilot.readthedocs.io/en/latest/serving/sky-serve.html) 🛫 from SkyPilot.
* **12/15/2023** [v0.7.0](https://github.com/TabbyML/tabby/releases/tag/v0.7.0) released with team management and secured access!
* **10/24/2023** ⛳️ Major updates for Tabby IDE plugins across [VSCode/Vim/IntelliJ](https://tabby.tabbyml.com/docs/extensions)!



<details>
  <summary>Archived</summary>

* **10/15/2023** RAG-based code completion is enabled by detail in [v0.3.0](https://github.com/TabbyML/tabby/releases/tag/v0.3.0)🎉! Check out the [blogpost](https://tabby.tabbyml.com/blog/2023/10/16/repository-context-for-code-completion/) explaining how Tabby utilizes repo-level context to get even smarter!
* **11/27/2023** [v0.6.0](https://github.com/TabbyML/tabby/releases/tag/v0.6.0) released!
* **11/09/2023** [v0.5.5](https://github.com/TabbyML/tabby/releases/tag/v0.5.5) released! With a redesign of UI + performance improvement.
* **10/04/2023** Check out the [model directory](https://tabby.tabbyml.com/docs/models/) for the latest models supported by Tabby.
* **09/18/2023** Apple's M1/M2 Metal inference support has landed in [v0.1.1](https://github.com/TabbyML/tabby/releases/tag/v0.1.1)!
* **08/31/2023** Tabby's first stable release [v0.0.1](https://github.com/TabbyML/tabby/releases/tag/v0.0.1) 🥳.
* **08/28/2023** Experimental support for the [CodeLlama 7B](https://github.com/TabbyML/tabby/issues/370).
* **08/24/2023** Tabby is now on [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/22379-tabby)!

</details>

## 👋 Getting Started

You can find our documentation [here](https://tabby.tabbyml.com/docs/getting-started).
- 📚 [Installation](https://tabby.tabbyml.com/docs/installation/)
- 💻 [IDE/Editor Extensions](https://tabby.tabbyml.com/docs/extensions/)
- ⚙️ [Configuration](https://tabby.tabbyml.com/docs/configuration)

### Run Tabby in 1 Minute
The easiest way to start a Tabby server is by using the following Docker command:

\`\`\`bash
docker run -it \\
  --gpus all -p 8080:8080 -v \$HOME/.tabby:/data \\
  tabbyml/tabby \\
  serve --model TabbyML/StarCoder-1B --device cuda
\`\`\`
For additional options (e.g inference type, parallelism), please refer to the [documentation page](https://tabbyml.github.io/tabby).

## 🤝 Contributing

Full guide at [CONTRIBUTING.md](https://github.com/TabbyML/tabby/blob/main/CONTRIBUTING.md);

### Get the Code

\`\`\`bash
git clone --recurse-submodules https://github.com/TabbyML/tabby
cd tabby
\`\`\`

If you have already cloned the repository, you could run the \`git submodule update --recursive --init\` command to fetch all submodules.

### Build

1. Set up the Rust environment by following this [tutorial](https://www.rust-lang.org/learn/get-started).

2. Install the required dependencies:
\`\`\`bash
# For MacOS
brew install protobuf

# For Ubuntu / Debian
apt-get install protobuf-compiler libopenblas-dev
\`\`\`

3. Now, you can build Tabby by running the command \`cargo build\`.

### Start Hacking!
... and don't forget to submit a [Pull Request](https://github.com/TabbyML/tabby/compare)

## 🌍 Community
- 🎤 [Twitter / X](https://twitter.com/Tabby_ML) - engage with TabbyML for all things possible 
- 📚 [LinkedIn](https://www.linkedin.com/company/tabbyml/) - follow for the latest from the community 
- 💌 [Newsletter](https://newsletter.tabbyml.com/archive) - subscribe to unlock Tabby insights and secrets



### 🌟 Star History

[![Star History Chart](https://api.star-history.com/svg?repos=tabbyml/tabby&type=Date)](https://star-history.com/#tabbyml/tabby&Date)

URL: [tabby/README.md](https://github.com/TabbyML/tabby/blob/main/README.md?plain=1)

#### Suggested labels
#### </details>

### #640: README.md · defog/sqlcoder-7b-2 at main
<details><summary>### Details</summary>Similarity score: 0.83
- [ ] [README.md · defog/sqlcoder-7b-2 at main](https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true)


# README.md · defog/sqlcoder-7b-2 at main

**DESCRIPTION:**
```yaml
license: cc-by-sa-4.0
library_name: transformers
pipeline_tag: text-generation
```

## Update notice
The model weights were updated at 7 AM UTC on Feb 7, 2024. The new model weights lead to a much more performant model – particularly for joins.

If you downloaded the model before that, please redownload the weights for best performance.

## Model Card for SQLCoder-7B-2

A capable large language model for natural language to SQL generation.

![image/png](https://cdn-uploads.huggingface.co/production/uploads/603bbad3fd770a9997b57cb6/AYUE2y14vy2XkD9MZpScu.png)

### Model Details

#### Model Description



This is the model card of a 🤗 transformers model that has been pushed on the Hub. This model card has been automatically generated.

- **Developed by:** [Defog, Inc](https://defog.ai)
- **Model type:** [Text to SQL]
- **License:** [CC-by-SA-4.0]
- **Finetuned from model:** [CodeLlama-7B]

#### Model Sources [optional]
- [**HuggingFace:**](https://huggingface.co/defog/sqlcoder-70b-alpha)
- [**GitHub:**](https://github.com/defog-ai/sqlcoder)
- [**Demo:**](https://defog.ai/sqlcoder-demo/)

## Uses

This model is intended to be used by non-technical users to understand data inside their SQL databases. It is meant as an analytics tool, and not as a database admin tool.

This model has not been trained to reject malicious requests from users with write access to databases, and should only be used by users with read-only access.

## How to Get Started with the Model

Use the code [here](https://github.com/defog-ai/sqlcoder/blob/main/inference.py) to get started with the model.

## Prompt

Please use the following prompt for optimal results. Please remember to use `do_sample=False` and `num_beams=4` for optimal results.

```
### Task
Generate a SQL query to answer [QUESTION]{user_question}[/QUESTION]
### Database Schema
The query will run on a database with the following schema:
{table_metadata_string_DDL_statements}
### Answer
Given the database schema, here is the SQL query that [QUESTION]{user_question}[/QUESTION]
[SQL]
```

## Evaluation

This model was evaluated on [SQL-Eval](https://github.com/defog-ai/sql-eval), a PostgreSQL based evaluation framework developed by Defog for testing and alignment of model capabilities.

You can read more about the methodology behind SQLEval [here](https://defog.ai/blog/open-sourcing-sqleval/).

### Results

We classified each generated question into one of 6 categories. The table displays the percentage of questions answered correctly by each model, broken down by category.

|                | date | group_by | order_by | ratio | join | where |
| -------------- | ---- | -------- | -------- | ----- | ---- | ----- |
| sqlcoder-70b   | 96   | 91.4     | 97.1     | 85.7  | 97.1 | 91.4  |
| sqlcoder-7b-2  | 96   | 91.4     | 94.3     | 91.4  | 94.3 | 77.1  |
| sqlcoder-34b   | 80   | 94.3     | 85.7     | 77.1  | 85.7 | 80    |
| gpt-4          | 72   | 94.3     | 97.1     | 80    | 91.4 | 80    |
| gpt-4-turbo    | 76   | 91.4     | 91.4     | 62.8  | 88.6 | 77.1  |
| natural-sql-7b | 56   | 88.6     | 85.7     | 60    | 88.6 | 80    |
| sqlcoder-7b    | 64   | 82.9     | 74.3     | 54.3  | 74.3 | 74.3  |
| gpt-3.5        | 72   | 77.1     | 82.8     | 34.3  | 65.7 | 71.4  |
| claude-2       | 52   | 71.4     | 74.3     | 57.1  | 65.7 | 62.9  |

## Model Card Contact

Contact us on X at [@defogdata](https://twitter.com/defogdata), or on email at [founders@defog.ai](mailto:founders@defog.ai)

**URL:** [https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true](https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true)

#### Suggested labels
#### </details>

### #325: simonw/llm pattern to migrate llm cli embeddings to chromadb
<details><summary>### Details</summary>Similarity score: 0.83
> **Note:**
> 
> - [ ] [Support for plugins that implement vector indexes · Issue #216 · simonw/llm](https://github.com/simonw/llm/issues/216)
> 
> @simonw happy to help here
> 
> Here is how Chroma's roadmap aligns with your goals.
> 
> The internals of Chroma are set up to have pluggable indexes on top of collections - we haven't yet exposed this to end users. But will fairly soon. We also plan to have a "smart index" that does KNN brute force and then a cutover to ANN.
> 
> Indexes over multiple collections - while I do understand the use case - we've chosen to not prioritize this as it adds a lot of DX complexity. We instead encourage users to eat the "read amplification" and query multiple collections/indexes and then cull/rerank themselves client side.
> 
> You may also enjoy reading this chroma proposal where we have put a lot of thought into the pipelines to support index/collection creation and access - [chroma-core/chroma#1110](https://github.com/chroma-core/chroma/issues/1110)
> 
> @dave1010 mentioned this issue 
> 
> Add option for RAG-style augmentation [dave1010/clipea#1](https://github.com/dave1010/clipea/issues/1)
> 
> Open
> 
> @IvanVas commented 
> 
> If someone ever need to move data from llm to Chroma, below is a simple script to do so. Needs a little more work to productise it though.
> 
> @simonw, hope it would help if you ever need to create smth like llm embed-multi migrate --chroma
> 
> ```python
> import sqlite3
> import struct
> import chromadb
> 
> def decode(binary):
>     if not isinstance(binary, bytes):
>         raise ValueError("Binary data must be of bytes type")
>     return struct.unpack("<" + "f" * (len(binary) // 4), binary)
> 
> client = chromadb.PersistentClient(path="chroma.db") # FIXME
> 
> collectionName = "collection" # FIXME
> collection = client.get_or_create_collection(collectionName)
> 
> # Path to your SQLite database
> db_path = "/Users/username/Library/Application Support/io.datasette.llm/embeddings.db" # FIXME
> 
> # Query to retrieve embeddings
> llm_collection = "fixme" # FIXME
> query = f"""
> SELECT id, embedding, content FROM embeddings WHERE collection_id = (
>     SELECT id FROM collections WHERE name = "{llm_collection}" 
> )
> """
> 
> def parse_id(id_str):
>     # FIXME parse metadata
> 
>     return {
>         "meta1": "meta1",
>     }
> 
> def main(db_path, batch_size=1000):
>     # Connect to the SQLite database
>     conn = sqlite3.connect(db_path)
>     cursor = conn.cursor()
> 
>     # Query the embeddings table
>     cursor.execute(query)
>     rows = cursor.fetchall() # FIXME assumes there is not MUCH data, works fine for x100k records
> 
>     # Initialize batch variables
>     batch_embeddings = []
>     batch_documents = []  # You'll need to adjust how you handle documents
>     batch_metadatas = []  # You'll need to adjust how you handle metadatas
>     batch_ids = []
> 
>     for i, (id, embedding, content) in enumerate(rows):
>         idParsed = parse_id(id)
> 
>         # Decode the binary data
>         decoded_embedding = decode(embedding)
> 
>         # Append to the batch
>         batch_embeddings.append(list(decoded_embedding))
>         batch_documents.append(content)
>         batch_metadatas.append({"meta1": idParsed['meta1']}) # FIXME
>         batch_ids.append(id)
> 
>         # When batch size is reached or end of rows
>         if len(batch_embeddings) == batch_size or i == len(rows) - 1:
>             collection.add(
>                 embeddings=batch_embeddings,
>                 documents=batch_documents,
>                 metadatas=batch_metadatas,
>                 ids=batch_ids
>             )
> 
>             print(f"Added {len(batch_embeddings)} rows to chromaDb (Total: {i + 1})")
> 
>             # Reset batch variables
>             batch_embeddings = []
>             batch_documents = []
>             batch_metadatas = []
>             batch_ids = []
> 
>     # Close the database connection
>     conn.close()
> 
> if __name__ == "__main__":
>     main(db_path)
> ```
> 
> #### Suggested labels
> 
> - { "key": "llm-inference-engines", "value": "Software and tools for running inference on Large Language Models (LLMs)" }
> - { "key": "llm-quantization", "value": "All about quantized LLM models and their serving" }</details>
