### ISSUE TITLE
Foreign data wrappers - PostgreSQL wiki

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#700]
- [ ] [Foreign data wrappers - PostgreSQL wiki](https://wiki.postgresql.org/wiki/Foreign_data_wrappers)

# Foreign data wrappers - PostgreSQL wiki

**Description:**
Foreign data wrappers

Jump to navigationJump to search

**Contents**
1. Foreign Data Wrappers
   1.1 Generic SQL Database Wrappers
   1.2 Specific SQL Database Wrappers
   1.3 NoSQL Database Wrappers
   1.4 File Wrappers
   1.5 Geo Wrappers
   1.6 LDAP Wrappers
   1.7 Generic Web Wrappers
   1.8 Specific Web Wrappers
   1.9 Big Data Wrappers
   1.10 Column-Oriented Wrappers
   1.11 Scientific Wrappers
   1.12 Operating System Wrappers
   1.13 Exotic Wrappers
   1.14 Example Wrappers
2. Writing Foreign Database Wrappers

**Foreign Data Wrappers**

In 2003, a new specification called SQL/MED ("SQL Management of External Data") was added to the SQL standard. It is a standardized way of handling access to remote objects from SQL databases. In 2011, PostgreSQL 9.1 was released with read-only support of this standard, and in 2013 write support was added with PostgreSQL 9.3.
There are now a variety of Foreign Data Wrappers (FDW) available which enable PostgreSQL Server to different remote data stores, ranging from other SQL databases through to flat file. This page list some of the wrappers currently available. Another fdw list can be found at the PGXN website.
Please keep in mind that most of these wrappers are not officially supported by the PostgreSQL Global Development Group (PGDG) and that some of these projects are still in Beta version. Use carefully!

**URL:** [Foreign data wrappers - PostgreSQL wiki](https://wiki.postgresql.org/wiki/Foreign_data_wrappers)

#### {'label-name': 'sql', 'label-description': 'Relational database language', 'confidence': 50.03}

**Comment by irthomasthomas** [comment]
### Related content
### #688: List of Foreign Data Wrappers from PostgreSQL Extension Network
<details><summary>### Details</summary>Similarity score: 0.91
- [ ] [Tag: “fdw” / PostgreSQL Extension Network](https://pgxn.org/tag/fdw/)


# Title: Tag: "fdw" / PostgreSQL Extension Network

**Description:**
Users tags recent Tag: "fdw" Distributions

- couchdb_fdw 0.1.0
  PostgreSQL SQL/MED FDW for CouchDB 2011-08-25
- cstore_fdw 1.7.0
  Columnar Store for PostgreSQL 2020-02-18
- firebird_fdw 1.3.0
  A PostgreSQL foreign data wrapper (FDW) for Firebird 2022-12-28
- foreign_table_exposer 1.0.0
  Expose foreign tables as a regular table 2015-12-18
- git_fdw 1.0.2
  PostgreSQL Git Foreign Data Wrapper 2017-09-12
- jdbc_fdw 1.0.0
  jdbc FDW for PostgreSQL 9.1+ 2013-04-20
- json_fdw 1.0.0
  Foreign Data Wrapper for JSON files 2013-11-18
- ldap_fdw 0.1.1
  LDAP Foreign Data Wrapper for PostgreSQL 9.2 2013-04-01
- mongo_fdw 2.0.0
  Foreign Data Wrapper for MongoDB 2013-11-18
- multicdr_fdw 1.2.2
  MultiCDR FDW 2012-10-26
- multicorn 1.4.0
  Multicorn Python bindings for Postgres 9.2+ Foreign Data Wrapper 2020-03-11
- mysql_fdw 2.1.2
  MySQL FDW for PostgreSQL 9.3+ 2016-01-22
- odbc_fdw 0.1.0
  PostgreSQL SQL/MED FDW for ODBC API 2011-08-25
- ogr_fdw 1.0.9
  OGR foreign data wrapper 2019-11-04
- oracle_fdw 2.6.0
  A Foreign Data Wrapper for Oracle 2023-09-08
- orb_fdw 0.0.3
  A foreign data wrapper for Orb 2024-02-08
- osm_fdw 4.1.2
  Openstreetmap PBF foreign data wrapper 2021-10-15
- pg_pathman 1.5.2
  Fast partitioning tool for PostgreSQL 2018-10-08
- pg_sqlog 1.4.0
  An extension providing access to PostgreSQL logs through SQL interface 2021-02-25
- postgres_fdw 1.0.0
  A read-only Postgres FDW for 9.2 2013-06-26
- redis_fdw 1.0.0
  Redis FDW for PostgreSQL 9.1+ 2011-08-27
- s3_fdw 0.2.0 (unstable)
  foreign-data wrapper for Amazon S3 2011-09-02
- sqlite_fdw 2.4.0
  Foreign Data Wrapper for SQLite databases 2023-09-29
- tds_fdw 1.0.7
  TDS Foreign data wrapper 2016-01-06
- treasuredata_fdw 1.2.15
  PostgreSQL Foreign Data Wrapper for Treasure Data 2020-04-29
- twitter_fdw 1.1.1
  a foreign data wrapper to Twitter Search 2012-06-02
- www_fdw 0.1.8
  FDW extension for different web services 2014-11-13

**Blog | Mastodon | Release on PGXN About | FAQ | Mirroring | Feedback**

**URL:** [https://pgxn.org/tag/fdw/](https://pgxn.org/tag/fdw/)

#### Suggested labels
#### </details>

### #623: Postgres Plugin for Steampipe 
<details><summary>### Details</summary>Similarity score: 0.84
- [ ] [Postgres Plugin for Steampipe ](https://github.com/jreyesr/steampipe-plugin-postgres)


# Postgres Plugin for Steampipe

**DESCRIPTION:**

Apache-2.0 license
Postgres Plugin for Steampipe

Use SQL to query data from plain PostgreSQL databases.

This repo contains a Steampipe plugin that exposes plain PostgreSQL databases as Steampipe tables, much like the CSV plugin does for CSV files, or like a reverse proxy does for HTTP. This can be used to join API data with semi-static data that is hosted on databases.

See below for an example that mixes data from a static DB (contact information for the teams that own Kubernetes namespaces) and data from Kubernetes (which namespaces have Failed pods). This may be part of an automated alerting system that runs periodically and sends emails.

**URL:** [https://github.com/jreyesr/steampipe-plugin-postgres](https://github.com/jreyesr/steampipe-plugin-postgres)

#### Suggested labels
#### {'label-name': 'Database Integration', 'label-description': 'Tools and plugins for integrating databases into Steampipe queries.', 'gh-repo': 'https://github.com/jreyesr/steampipe-plugin-postgres', 'confidence': 57.69}</details>

### #74: Sqlite WASM and Github Pages
<details><summary>### Details</summary>Similarity score: 0.83
- [ ] [merge sqlite - Kagi Search](https://kagi.com/search?q=merge+sqlite&from_date=2021-01-01)
- [ ] [sql - Fastest Way merge two SQLITE Databases - Stack Overflow](https://stackoverflow.com/questions/9349659/fastest-way-merge-two-sqlite-databases)
- [ ] [simonw/sqlite-utils: Python CLI utility and library for manipulating SQLite databases](https://github.com/simonw/sqlite-utils)
- [ ] [sqlite-utils](https://sqlite-utils.datasette.io/en/stable/)
- [ ] [GitHub Pages | Websites for you and your projects, hosted directly from your GitHub repository. Just edit, push, and your changes are live.](https://pages.github.com/)
- [ ] [sqlite wasm sql.js github pages - Kagi Search](https://kagi.com/search?q=sqlite+wasm+sql.js+github+pages)
- [ ] [phiresky/sql.js-httpvfs: Hosting read-only SQLite databases on static file hosters like Github Pages](https://github.com/phiresky/sql.js-httpvfs)
- [ ] [sqlite3 WebAssembly & JavaScript Documentation Index](https://sqlite.org/wasm/doc/trunk/index.md)
- [ ] [phiresky/youtube-sponsorship-stats/](https://github.com/phiresky/youtube-sponsorship-stats/)
- [ ] [phiresky/world-development-indicators-sqlite/](https://github.com/phiresky/world-development-indicators-sqlite/)
- [ ] [Show HN: Fully-searchable Library Genesis on IPFS | Hacker News](https://news.ycombinator.com/item?id=28585208)
- [ ] [nalgeon/sqlime: Online SQLite playground](https://github.com/nalgeon/sqlime)
- [ ] [nalgeon/sqlean.js: Browser-based SQLite with extensions](https://github.com/nalgeon/sqlean.js)
- [ ] [Sqlime - SQLite Playground](https://sqlime.org/)
- [ ] [sqlite-wasm-http - npm](https://www.npmjs.com/package/sqlite-wasm-http)
- [ ] [Postgres WASM by Snaplet and Supabase](https://supabase.com/blog/postgres-wasm)
- [ ] [rhashimoto/wa-sqlite: WebAssembly SQLite with experimental support for browser storage extensions](https://github.com/rhashimoto/wa-sqlite)
- [ ] [jlongster/absurd-sql: sqlite3 in ur indexeddb (hopefully a better backend soon)](https://github.com/jlongster/absurd-sql)
- [ ] [help: basic example for the web browser · Issue #23 · phiresky/sql.js-httpvfs](https://github.com/phiresky/sql.js-httpvfs/issues/23)
- [ ] [phiresky/sql.js-httpvfs: Hosting read-only SQLite databases on static file hosters like Github Pages](https://github.com/phiresky/sql.js-httpvfs#minimal-example-from-scratch)
- [ ] [sql.js-httpvfs/example at master · phiresky/sql.js-httpvfs](https://github.com/phiresky/sql.js-httpvfs/tree/master/example)
- [ ] [Code search results](https://github.com/search?utf8=%E2%9C%93&q=sql.js-httpvfs&type=code)
- [ ] [knowledge/docs/databases/sqlite.md at 7c4bbc755c64368a82ca22b76566e9153cd2e377 · nikitavoloboev/knowledge](https://github.com/nikitavoloboev/knowledge/blob/7c4bbc755c64368a82ca22b76566e9153cd2e377/docs/databases/sqlite.md?plain=1#L96)
- [ ] [static-wiki/src/sqlite.js at b0ae18ed02ca64263075c3516c38a504f46e10c4 · segfall/static-wiki](https://github.com/segfall/static-wiki/blob/b0ae18ed02ca64263075c3516c38a504f46e10c4/src/sqlite.js#L2)
</details>

### #545: Pragma statements supported by SQLite
<details><summary>### Details</summary>Similarity score: 0.82
- [ ] [https://sqlite.org/pragma.html](https://sqlite.org/pragma.html#toc)


# Pragma statements supported by SQLite

## Description
The PRAGMA statement is an SQL extension specific to SQLite and used to modify the operation of the SQLite library or to query the SQLite library for internal (non-table) data. The PRAGMA statement is issued using the same interface as other SQLite commands (e.g. SELECT, INSERT) but is different in the following important respects:

- The pragma command is specific to SQLite and is not compatible with any other SQL database engine.
- Specific pragma statements may be removed and others added in future releases of SQLite. There is no guarantee of backwards compatibility.
- No error messages are generated if an unknown pragma is issued. Unknown pragmas are simply ignored. This means if there is a typo in a pragma statement the library does not inform the user of the fact.
- Some pragmas take effect during the SQL compilation stage, not the execution stage. This means if using the C-language sqlite3_prepare(), sqlite3_step(), sqlite3_finalize() API (or similar in a wrapper interface), the pragma may run during the sqlite3_prepare() call, not during the sqlite3_step() call as normal SQL statements do. Or the pragma might run during sqlite3_step() just like normal SQL statements. Whether or not the pragma runs during sqlite3_prepare() or sqlite3_step() depends on the pragma and on the specific release of SQLite.
- The EXPLAIN and EXPLAIN QUERY PLAN prefixes to SQL statements only affect the behavior of the statement during sqlite3_step(). That means that PRAGMA statements that take effect during sqlite3_prepare() will behave the same way regardless of whether or not they are prefaced by "EXPLAIN".
- The C-language API for SQLite provides the SQLITE_FCNTL_PRAGMA file control which gives VFS implementations the opportunity to add new PRAGMA statements or to override the meaning of built-in PRAGMA statements.

## PRAGMA Command Syntax
```sql
PRAGMA schema-name.pragma-name(pragma-value) = pragma-value
```

- A pragma can take either zero or one argument. The argument is may be either in parentheses or it may be separated from the pragma name by an equal sign. The two syntaxes yield identical results. In many pragmas, the argument is a boolean. The boolean can be one of:
  - 1, yes, true, on
  - 0, no, false, off

- Keyword arguments can optionally appear in quotes. (Example: 'yes' [FALSE].) Some pragmas takes a string literal as their argument. When pragma takes a keyword argument, it will usually also take a numeric equivalent as well. For example, "0" and "no" mean the same thing, as does "1" and "yes". When querying the value of a setting, many pragmas return the number rather than the keyword.

- A pragma may have an optional schema-name before the pragma name. The schema-name is the name of an ATTACH-ed database or "main" or "temp" for the main and the TEMP databases. If the optional schema name is omitted, "main" is assumed. In some pragmas, the schema name is meaningless and is simply ignored. In the documentation below, pragmas for which the schema name is meaningful are shown with a "schema." prefix.

## PRAGMA Functions
PRAGMAs that return results and that have no side-effects can be accessed from ordinary SELECT statements as table-valued functions. For each participating PRAGMA, the corresponding table-valued function has the same name as the PRAGMA with a 7-character "pragma_" prefix. The PRAGMA argument and schema, if any, are passed as arguments to the table-valued function, with the schema as an optional, last argument.

For example, information about the columns in an index can be read using the index_info pragma as follows:
```sql
PRAGMA index_info('idx52');
```
Or, the same content can be read using:
```sql
SELECT * FROM pragma_index_info('idx52');
```

The advantage of the table-valued function format is that the query can return just a subset of the PRAGMA columns, can include a WHERE clause, can use aggregate functions, and the table-valued function can be just one of several data sources in a join. For example, to get a list of all indexed columns in a schema, one could query:
```sql
SELECT DISTINCT m.name || '.' || ii.name AS 'indexed-columns'
  FROM sqlite_schema AS m,
       pragma_index_list(m.name) AS il,
       pragma_index_info(il.name) AS ii
 WHERE m.type='table'
 ORDER BY 1;
```

Additional notes:
- Table-valued functions exist only for built-in PRAGMAs, not for PRAGMAs defined using the SQLITE_FCNTL_PRAGMA file control.
- Table-valued functions exist only for PRAGMAs that return results and that have no side-effects.
- This feature could be used to implement information schema by first creating a separate schema using
```sql
ATTACH ':memory:' AS 'information_schema';
```
Then creating VIEWs in that schema that implement the official information schema tables using table-valued PRAGMA functions.

The table-valued functions for PRAGMA feature was added in SQLite version 3.16.0 (2017-01-02). Prior versions of SQLite cannot use this feature.

[More information](https://sqlite.org/pragma.html#toc)

#### Suggested labels
#### {'label-name': 'SQL commands', 'label-description': 'Descriptions and syntax of SQL commands specific to SQLite.', 'confidence': 66.84}</details>

### #640: README.md · defog/sqlcoder-7b-2 at main
<details><summary>### Details</summary>Similarity score: 0.82
- [ ] [README.md · defog/sqlcoder-7b-2 at main](https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true)


# README.md · defog/sqlcoder-7b-2 at main

**DESCRIPTION:**
```yaml
license: cc-by-sa-4.0
library_name: transformers
pipeline_tag: text-generation
```

## Update notice
The model weights were updated at 7 AM UTC on Feb 7, 2024. The new model weights lead to a much more performant model – particularly for joins.

If you downloaded the model before that, please redownload the weights for best performance.

## Model Card for SQLCoder-7B-2

A capable large language model for natural language to SQL generation.

![image/png](https://cdn-uploads.huggingface.co/production/uploads/603bbad3fd770a9997b57cb6/AYUE2y14vy2XkD9MZpScu.png)

### Model Details

#### Model Description



This is the model card of a 🤗 transformers model that has been pushed on the Hub. This model card has been automatically generated.

- **Developed by:** [Defog, Inc](https://defog.ai)
- **Model type:** [Text to SQL]
- **License:** [CC-by-SA-4.0]
- **Finetuned from model:** [CodeLlama-7B]

#### Model Sources [optional]
- [**HuggingFace:**](https://huggingface.co/defog/sqlcoder-70b-alpha)
- [**GitHub:**](https://github.com/defog-ai/sqlcoder)
- [**Demo:**](https://defog.ai/sqlcoder-demo/)

## Uses

This model is intended to be used by non-technical users to understand data inside their SQL databases. It is meant as an analytics tool, and not as a database admin tool.

This model has not been trained to reject malicious requests from users with write access to databases, and should only be used by users with read-only access.

## How to Get Started with the Model

Use the code [here](https://github.com/defog-ai/sqlcoder/blob/main/inference.py) to get started with the model.

## Prompt

Please use the following prompt for optimal results. Please remember to use `do_sample=False` and `num_beams=4` for optimal results.

```
### Task
Generate a SQL query to answer [QUESTION]{user_question}[/QUESTION]
### Database Schema
The query will run on a database with the following schema:
{table_metadata_string_DDL_statements}
### Answer
Given the database schema, here is the SQL query that [QUESTION]{user_question}[/QUESTION]
[SQL]
```

## Evaluation

This model was evaluated on [SQL-Eval](https://github.com/defog-ai/sql-eval), a PostgreSQL based evaluation framework developed by Defog for testing and alignment of model capabilities.

You can read more about the methodology behind SQLEval [here](https://defog.ai/blog/open-sourcing-sqleval/).

### Results

We classified each generated question into one of 6 categories. The table displays the percentage of questions answered correctly by each model, broken down by category.

|                | date | group_by | order_by | ratio | join | where |
| -------------- | ---- | -------- | -------- | ----- | ---- | ----- |
| sqlcoder-70b   | 96   | 91.4     | 97.1     | 85.7  | 97.1 | 91.4  |
| sqlcoder-7b-2  | 96   | 91.4     | 94.3     | 91.4  | 94.3 | 77.1  |
| sqlcoder-34b   | 80   | 94.3     | 85.7     | 77.1  | 85.7 | 80    |
| gpt-4          | 72   | 94.3     | 97.1     | 80    | 91.4 | 80    |
| gpt-4-turbo    | 76   | 91.4     | 91.4     | 62.8  | 88.6 | 77.1  |
| natural-sql-7b | 56   | 88.6     | 85.7     | 60    | 88.6 | 80    |
| sqlcoder-7b    | 64   | 82.9     | 74.3     | 54.3  | 74.3 | 74.3  |
| gpt-3.5        | 72   | 77.1     | 82.8     | 34.3  | 65.7 | 71.4  |
| claude-2       | 52   | 71.4     | 74.3     | 57.1  | 65.7 | 62.9  |

## Model Card Contact

Contact us on X at [@defogdata](https://twitter.com/defogdata), or on email at [founders@defog.ai](mailto:founders@defog.ai)

**URL:** [https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true](https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true)

#### Suggested labels
#### </details>

### #693: https://supabase.com/blog/postgres-wasm
<details><summary>### Details</summary>Similarity score: 0.82
- [ ] [https://supabase.com/blog/postgres-wasm](https://supabase.com/blog/postgres-wasm)


# Title: [Postgres WASM by Snaplet and Supabase](https://supabase.com/blog/postgres-wasm)

**Description:** Postgres WASM by Snaplet and Supabase
2022-10-03
•
11 minute read
Mark Burggraf avatar
Mark Burggraf
Engineering

Postgres WASM by Snaplet and Supabase

Today we're open sourcing postgres-wasm with our friends at Snaplet.

postgres-wasm is a PostgreSQL server that runs inside a browser. It provides a full suite of features, including persisting state to browser, restoring from pg_dump, and logical replication from a remote database.

We're not the first to run Postgres in the browser - that title belongs to the team at Crunchy Data who shared their version of this on HN a month ago. It's awesome, and we wanted an open source version, so we teamed up with Snaplet build it. Let's explore how it's built, and some extra features we've added.

🐈 Who's Snaplet?

Snaplet gives developers production-accurate data and preview databases that they can code against, so they can focus on shipping.

Checkout out how you can use Snaplet to clone Supabase environments.

**Demo**

Before we get into the technical details, try it out yourself (warning: it will download ~30MB):

[wasm.supabase.com](https://wasm.supabase.com)

**Postgres inside a browser**

To run it locally:

```bash
# From Snaplet Repo
git clone git@github.com:snaplet/postgres-wasm.git
cd postgres-browser/packages/pg-browser
npx serve

# From Supabase Fork
git clone git@github.com:supabase-community/postgres-wasm.git
cd postgres-wasm
git checkout web
cd packages/supabrowser
npx serve
```

And open a browser at localhost:3000.

**URL:** [https://supabase.com/blog/postgres-wasm](https://supabase.com/blog/postgres-wasm)

#### Suggested labels
#### {'label-name': 'WebAssembly', 'label-description': 'Technology that enables running high-performance applications in web browsers.', 'confidence': 76.53}</details>
