### ISSUE TITLE
Getting Started | Defog Docs

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#702]
- [ ] [Getting Started | Defog Docs](https://docs.defog.ai/getting-started/)

# Getting Started | Defog Docs

**Description:**  
Let's discover Defog in less than 5 minutes. Here's a 1-minute demo of the setup.

**What you'll need:**
- A Defog API Key. Sign up [here](https://docs.defog.ai/getting-started/) for a free API key.
- Python 3
- Pip
- Drivers for your database

If you do not have pip installed on your computer, you can install it [here](https://docs.defog.ai/getting-started/).

**Initializing Defog:**

Get started by installing our CLI interface.

To do this, just run the following commands on your terminal:

```bash
pip install --upgrade 'defog[snowflake]'
```

If you're not using Snowflake, then you can replace the above with:

```bash
pip install --upgrade 'defog[postgres]'
```
or
```bash
pip install --upgrade 'defog[mysql]'
```
or
```bash
pip install --upgrade 'defog[bigquery]'
```

```bash
defog init
```

From here, you can just follow the instructions in the CLI wizard to get started!

**Important Note:** Doing this does not send your database credentials to Defog! This is only done so we can get your database metadata (table names, column names, column descriptions), and so you can execute the queries generated by Defog locally on your machine.

**Generating a CSV file for your metadata:**

To generate a CSV file that contains your metadata, just list all the tables names you want, separated by a space.

```bash
defog gen <table1> <table2> <table3> ...
```

Once generated, you can edit the CSV to give an accurate description of your metadata. We have included steps to do that in this Cookbook.

**Uploading your metadata:**

To upload your metadata to Defog, just pass in the path to your CSV via `defog update`.

```bash
defog update path_to_metadata_csv
```

For example, if your CSV is in the current folder as `defog_metadata.csv`, you should just run `defog update defog_metadata.csv`.

**Making a test query:**

Once your metadata has been updated, you can start making test queries. An example query is below:

```bash
defog query 'how many users do we have?'
```

**(Optional) Deploying to AWS Lambda or GCP Functions:**

If you want to deploy Defog as a microservice on your cloud, you can run the following functions:

```bash
# for AWS Lambda
# before this, you must install chalice with `pip install chalice`
defog deploy aws
```

```bash
# for GCP Functions
# before this, you must have gcloud installed on your machine
defog deploy gcp
```

Once you do this, you will see the API endpoint for your microservice in your console.

**URL:** [https://docs.defog.ai/getting-started/](https://docs.defog.ai/getting-started/)

####

**Comment by irthomasthomas** [comment]
### Related content
### #688: List of Foreign Data Wrappers from PostgreSQL Extension Network
<details><summary>### Details</summary>Similarity score: 0.86
- [ ] [Tag: “fdw” / PostgreSQL Extension Network](https://pgxn.org/tag/fdw/)


# Title: Tag: "fdw" / PostgreSQL Extension Network

**Description:**
Users tags recent Tag: "fdw" Distributions

- couchdb_fdw 0.1.0
  PostgreSQL SQL/MED FDW for CouchDB 2011-08-25
- cstore_fdw 1.7.0
  Columnar Store for PostgreSQL 2020-02-18
- firebird_fdw 1.3.0
  A PostgreSQL foreign data wrapper (FDW) for Firebird 2022-12-28
- foreign_table_exposer 1.0.0
  Expose foreign tables as a regular table 2015-12-18
- git_fdw 1.0.2
  PostgreSQL Git Foreign Data Wrapper 2017-09-12
- jdbc_fdw 1.0.0
  jdbc FDW for PostgreSQL 9.1+ 2013-04-20
- json_fdw 1.0.0
  Foreign Data Wrapper for JSON files 2013-11-18
- ldap_fdw 0.1.1
  LDAP Foreign Data Wrapper for PostgreSQL 9.2 2013-04-01
- mongo_fdw 2.0.0
  Foreign Data Wrapper for MongoDB 2013-11-18
- multicdr_fdw 1.2.2
  MultiCDR FDW 2012-10-26
- multicorn 1.4.0
  Multicorn Python bindings for Postgres 9.2+ Foreign Data Wrapper 2020-03-11
- mysql_fdw 2.1.2
  MySQL FDW for PostgreSQL 9.3+ 2016-01-22
- odbc_fdw 0.1.0
  PostgreSQL SQL/MED FDW for ODBC API 2011-08-25
- ogr_fdw 1.0.9
  OGR foreign data wrapper 2019-11-04
- oracle_fdw 2.6.0
  A Foreign Data Wrapper for Oracle 2023-09-08
- orb_fdw 0.0.3
  A foreign data wrapper for Orb 2024-02-08
- osm_fdw 4.1.2
  Openstreetmap PBF foreign data wrapper 2021-10-15
- pg_pathman 1.5.2
  Fast partitioning tool for PostgreSQL 2018-10-08
- pg_sqlog 1.4.0
  An extension providing access to PostgreSQL logs through SQL interface 2021-02-25
- postgres_fdw 1.0.0
  A read-only Postgres FDW for 9.2 2013-06-26
- redis_fdw 1.0.0
  Redis FDW for PostgreSQL 9.1+ 2011-08-27
- s3_fdw 0.2.0 (unstable)
  foreign-data wrapper for Amazon S3 2011-09-02
- sqlite_fdw 2.4.0
  Foreign Data Wrapper for SQLite databases 2023-09-29
- tds_fdw 1.0.7
  TDS Foreign data wrapper 2016-01-06
- treasuredata_fdw 1.2.15
  PostgreSQL Foreign Data Wrapper for Treasure Data 2020-04-29
- twitter_fdw 1.1.1
  a foreign data wrapper to Twitter Search 2012-06-02
- www_fdw 0.1.8
  FDW extension for different web services 2014-11-13

**Blog | Mastodon | Release on PGXN About | FAQ | Mirroring | Feedback**

**URL:** [https://pgxn.org/tag/fdw/](https://pgxn.org/tag/fdw/)

#### Suggested labels
#### </details>

### #623: Postgres Plugin for Steampipe 
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [Postgres Plugin for Steampipe ](https://github.com/jreyesr/steampipe-plugin-postgres)


# Postgres Plugin for Steampipe

**DESCRIPTION:**

Apache-2.0 license
Postgres Plugin for Steampipe

Use SQL to query data from plain PostgreSQL databases.

This repo contains a Steampipe plugin that exposes plain PostgreSQL databases as Steampipe tables, much like the CSV plugin does for CSV files, or like a reverse proxy does for HTTP. This can be used to join API data with semi-static data that is hosted on databases.

See below for an example that mixes data from a static DB (contact information for the teams that own Kubernetes namespaces) and data from Kubernetes (which namespaces have Failed pods). This may be part of an automated alerting system that runs periodically and sends emails.

**URL:** [https://github.com/jreyesr/steampipe-plugin-postgres](https://github.com/jreyesr/steampipe-plugin-postgres)

#### Suggested labels
#### {'label-name': 'Database Integration', 'label-description': 'Tools and plugins for integrating databases into Steampipe queries.', 'gh-repo': 'https://github.com/jreyesr/steampipe-plugin-postgres', 'confidence': 57.69}</details>

### #696: Defog Sqlcoder LLM - Cookbook for schema definitions
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [👨🏼‍🍳 Cookbook for schema definitions](https://defog.notion.site/Cookbook-for-schema-definitions-1650a6855ea447fdb0be75d39975571b)


# Cookbook for schema definitions

**DESCRIPTION:**  
Hello! This is a cookbook that helps you define schemas in a way that the Defog model can understand them better. Our auto-generated schemas work well for most cases, but they can fail if you have complex or domain-specific databases. If this happens, manually editing the schema definitions to give Defog more context will help generate better queries. We have seen a 90+% reduction in query errors when customers define their schemas well!

**Column definitions:**  
When you write down what, exactly, is inside a column and how it is calculated - query quality improves significantly.

**Defining terms better:**  
Giving Defog more context for ambiguous terms helps improve query quality. Case in point here. Without the additional context in the pricepaid column, our model would be unsure about whether pricepaid is the price paid per ticket, or the total price paid for the listing. Similarly, without details about whether commission is a part of the price paid or not, we would have no idea about whether it is included in the pricepaid, or whether it is paid over and beyond the pricepaid.

When you give us more context about what your columns mean, query quality goes up significantly.

**URL:** [Cookbook for schema definitions](https://defog.notion.site/Cookbook-for-schema-definitions-1650a6855ea447fdb0be75d39975571b)

#### Suggested labels
#### {'label-name': 'data_schema_definition', 'label-description': 'Guidance on defining data schema for improved query quality', 'confidence': 51.56}</details>

### #640: README.md · defog/sqlcoder-7b-2 at main
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [README.md · defog/sqlcoder-7b-2 at main](https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true)


# README.md · defog/sqlcoder-7b-2 at main

**DESCRIPTION:**
```yaml
license: cc-by-sa-4.0
library_name: transformers
pipeline_tag: text-generation
```

## Update notice
The model weights were updated at 7 AM UTC on Feb 7, 2024. The new model weights lead to a much more performant model – particularly for joins.

If you downloaded the model before that, please redownload the weights for best performance.

## Model Card for SQLCoder-7B-2

A capable large language model for natural language to SQL generation.

![image/png](https://cdn-uploads.huggingface.co/production/uploads/603bbad3fd770a9997b57cb6/AYUE2y14vy2XkD9MZpScu.png)

### Model Details

#### Model Description



This is the model card of a 🤗 transformers model that has been pushed on the Hub. This model card has been automatically generated.

- **Developed by:** [Defog, Inc](https://defog.ai)
- **Model type:** [Text to SQL]
- **License:** [CC-by-SA-4.0]
- **Finetuned from model:** [CodeLlama-7B]

#### Model Sources [optional]
- [**HuggingFace:**](https://huggingface.co/defog/sqlcoder-70b-alpha)
- [**GitHub:**](https://github.com/defog-ai/sqlcoder)
- [**Demo:**](https://defog.ai/sqlcoder-demo/)

## Uses

This model is intended to be used by non-technical users to understand data inside their SQL databases. It is meant as an analytics tool, and not as a database admin tool.

This model has not been trained to reject malicious requests from users with write access to databases, and should only be used by users with read-only access.

## How to Get Started with the Model

Use the code [here](https://github.com/defog-ai/sqlcoder/blob/main/inference.py) to get started with the model.

## Prompt

Please use the following prompt for optimal results. Please remember to use `do_sample=False` and `num_beams=4` for optimal results.

```
### Task
Generate a SQL query to answer [QUESTION]{user_question}[/QUESTION]
### Database Schema
The query will run on a database with the following schema:
{table_metadata_string_DDL_statements}
### Answer
Given the database schema, here is the SQL query that [QUESTION]{user_question}[/QUESTION]
[SQL]
```

## Evaluation

This model was evaluated on [SQL-Eval](https://github.com/defog-ai/sql-eval), a PostgreSQL based evaluation framework developed by Defog for testing and alignment of model capabilities.

You can read more about the methodology behind SQLEval [here](https://defog.ai/blog/open-sourcing-sqleval/).

### Results

We classified each generated question into one of 6 categories. The table displays the percentage of questions answered correctly by each model, broken down by category.

|                | date | group_by | order_by | ratio | join | where |
| -------------- | ---- | -------- | -------- | ----- | ---- | ----- |
| sqlcoder-70b   | 96   | 91.4     | 97.1     | 85.7  | 97.1 | 91.4  |
| sqlcoder-7b-2  | 96   | 91.4     | 94.3     | 91.4  | 94.3 | 77.1  |
| sqlcoder-34b   | 80   | 94.3     | 85.7     | 77.1  | 85.7 | 80    |
| gpt-4          | 72   | 94.3     | 97.1     | 80    | 91.4 | 80    |
| gpt-4-turbo    | 76   | 91.4     | 91.4     | 62.8  | 88.6 | 77.1  |
| natural-sql-7b | 56   | 88.6     | 85.7     | 60    | 88.6 | 80    |
| sqlcoder-7b    | 64   | 82.9     | 74.3     | 54.3  | 74.3 | 74.3  |
| gpt-3.5        | 72   | 77.1     | 82.8     | 34.3  | 65.7 | 71.4  |
| claude-2       | 52   | 71.4     | 74.3     | 57.1  | 65.7 | 62.9  |

## Model Card Contact

Contact us on X at [@defogdata](https://twitter.com/defogdata), or on email at [founders@defog.ai](mailto:founders@defog.ai)

**URL:** [https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true](https://huggingface.co/defog/sqlcoder-7b-2/blob/main/README.md?code=true)

#### Suggested labels
#### </details>

### #461: Running Steampipe extensions in sqlite-utils and Datasette | Simon Willison’s TILs
<details><summary>### Details</summary>Similarity score: 0.85
- [ ] [Running Steampipe extensions in sqlite-utils and Datasette | Simon Willison’s TILs](https://til.simonwillison.net/sqlite/steampipe#user-content-running-extensions-in-datasette)

 # Running Steampipe extensions in `sqlite-utils` and Datasette

Steampipe is a build software that enables you to query different APIs directly from SQL databases. The original product was designed for PostgreSQL, but last week, they announced support for SQLite, along with ports of 100 of their existing extensions.

Here's the full list of SQLite extensions they released.

To install and use these extensions, you can either use their CLI tool or access the .so files directly via GitHub releases.

This guide will demonstrate how to run these extensions on a Mac using both `sqlite-utils` and Datasette.

# Downloading an extension

Let's start with the Hacker News API plugin, `turbot/steampipe-plugin-hackernews`. This plugin doesn't require an API key, making it a great choice for this example.

First, grab the latest release of the extension. For an M2 MacBook, download the `steampipe_sqlite_hackernews.darwin_arm64.tar.gz` file:
```bash
curl -OL https://github.com/turbot/steampipe-plugin-hackernews/releases/download/v0.8.1/steampipe_sqlite_hackernews.darwin_arm64.tar.gz
tar -xzvf steampipe_sqlite_hackernews.darwin_arm64.tar.gz
```
Now, you have a `steampipe_sqlite_hackernews.so` file.

# Loading extensions with `sqlite-utils`

With `sqlite-utils` installed, you can run the following command:
```bash
sqlite-utils memory --load-extension steampipe_sqlite_hackernews.so \
  'select id, title, time from hackernews_top limit 3'
```
This will produce a warning box due to the unsigned binary. To bypass this error, open the system Security preferences pane, find the option to allow unsigned binaries, and click "Allow Anyway". Then, try running the command again.

After allowing the extension, you'll see another dialog. Click "Open" to run the script correctly.

Now, you can run the command again:
```bash
sqlite-utils memory --load-extension steampipe_sqlite_hackernews.so \
  'select id, title, time from hackernews_top limit 3'
```
You should receive the response:
```json
[
  {
    "id": 38706914,
    "title": "Gameboy Music and Sound Archive for MIDI",
    "time": "2023-12-20 09:45:05"
  },
  {
    "id": 38717114,
    "title": "Show HN: Talk to any ArXiv paper just by changing the URL",
    "time": "2023-12-21 04:48:20"
  },
  {
    "id": 38716075,
    "title": "OpenAI Begins Tackling ChatGPT Data Leak Vulnerability",
    "time": "2023-12-21 01:38:10"
  }
]
```
You've successfully queried the Hacker News API using SQL!

# Running extensions in Datasette

After enabling an extension, it can be used directly with Datasette as well. Let's try using the `turbot/steampipe-plugin-crtsh` plugin for querying certificate transparency logs.

Download the latest `steampipe_sqlite_crtsh.darwin_arm64.tar.gz` file for macOS:
```bash
curl -OL https://github.com/turbot/steampipe-plugin-crtsh/releases/download/v0.4.0/steampipe_sqlite_crtsh.darwin_arm64.tar.gz
tar -xzvf steampipe_sqlite_crtsh.darwin_arm64.tar.gz
```
Now, load both extensions using Datasette:
```sql
datasette \
  --load-extension steampipe_sqlite_crtsh.so \
  --load-extension steampipe_sqlite_hackernews.so \
  --setting sql_time_limit_ms 20000
```
The `--setting sql_time_limit_ms 20000` line increases the default time limit on SQL queries from 1s to 20s, which is useful for some of these API calls since they can be a little slow.

You can now query the certificate transparency log with SQL:
```sql
select
  dns_names,
  not_after
from
  crtsh_certificate
where
  query = 'datasette.io'
order by not_after desc;
```
Here's a more complex query demonstrating a CTE, JSON processing, and a join across two virtual tables:
```sql
with post_ids as (
  select
    value
  from
    json_each(submitted),
    hackernews_user
  where
    hackernews_user.id = 'simonw'
  limit
    20
)

select
  *
from
  hackernews_item
where
  hackernews_item.id in (
    select
      value
    from
      post_ids
  )
order by time desc
```
For more information on the kind of queries you can run, refer to the following documentation:

Tables in crt.sh
Tables in Hacker News

#### Suggested labels
#### {   "label-name": "Steampipe",   "description": "Querying APIs from SQL databases with Steampipe extensions",   "confidence": 97.71 }</details>

### #644: cohereai_classify table | CohereAI plugin | Steampipe Hub
<details><summary>### Details</summary>Similarity score: 0.84
- [ ] [cohereai_classify table | CohereAI plugin | Steampipe Hub](https://hub.steampipe.io/plugins/mr-destructive/cohereai/tables/cohereai_classify)


# TITLE: cohereai_classify table | CohereAI plugin | Steampipe Hub

**DESCRIPTION:**
Overview
8Tables
Versions
GitHub
steampipe plugin install mr-destructive/cohereai

**cohereai_classify**
cohereai_detect_language
cohereai_detokenize
cohereai_embed
cohereai_generation
cohereai_summaraize
cohereai_summarize
cohereai_tokenize

**ON THIS PAGE**
Examples
Schema

**GET INVOLVED**
Edit on GitHub
Discuss on Slack

**Table: cohereai_classify**

Get classification for a given input strings and examples.

Notes:

- A inputs is a list of strings to classify.(max 96 strings)
- A examples is a list of {"text": "apple", "label": "fruit"} structure of type Example
- Minimum 2 examples should be provided and the maximum value is 2500 with each example of maximum of 512 tokens.

**Examples**

Basic classification with given set of inputs and examples

```sql
select
  classification
from
  cohereai_classify
where
  inputs = '["apple", "blue", "pineapple"]'
  and examples = '[{"text": "apple", "label": "fruit"}, {"text": "green", "label": "color"}, {"text": "grapes", "label": "fruit"}, {"text": "purple", "label": "color"}]';
```

Classification with specific settings(model, preset)

```sql
select
  classification
from
  cohereai_classify
where
  settings = '{
 "model": "embed - multilingual - v2.0" }'
  and inputs = '["Help!", "Call me when you can"]'
  and examples = '[{"text": "Help!", "label": "urgent"}, {"text": "SOS", "label": "urgent"}, {"text": "Call me when you can", "label": "not urgent"}, {"text": "Talk later?", "label": "not urgent"}]';
```

Email Spam Classification

```sql
select
  classification
from
  cohereai_classify
where
  inputs = '["Confirm your email address", "hey i need u to send some $"]'
  and examples = '[{"label": "Spam", "text": "Dermatologists don't like her!"}, {"label": "Spam", "text": "Hello, open to this?"}, {"label": "Spam", "text": "I need help please wire me $1000 right now"}, {"label": "Spam", "text": "Hot new investment, don't miss this!"}, {"label": "Spam", "text": "Nice to know you ;)"}, {"label": "Spam", "text": "Please help me?"}, {"label": "Not spam", "text": "Your parcel will be delivered today"}, {"label": "Not spam", "text": "Review changes to our Terms and Conditions"}, {"label": "Not spam", "text": "Weekly sync notes"}, {"label": "Not spam", "text": "Re: Follow up from today's meeting"}, {"label": "Not spam", "text": "Pre-read for tomorrow"}]';
```

**Schema for cohereai_classify**

| Name          | Type             | Operators | Description                                                  |
|---------------|------------------|-----------|--------------------------------------------------------------|
| _ctx          | jsonb            |           | Steampipe context in JSON form, e.g. connection_name.        |
| classification| text             |           | The classification results for the given input text(s).      |
| confidence    | double precision |           | The confidence score of the classification.                  |
| examples      | text             |           | The example text classified.                                 |
| id            | text             |           | The ID of the classification.                                |
| inputs        | text             |           | The input text that was classified.                          |
| labels        | jsonb            |           | The labels of the classification.                            |
| settings      | jsonb            |           | Settings is a JSONB object that accepts any of the classify API request parameters. |

**URL:** [cohereai_classify table | CohereAI plugin | Steampipe Hub](https://hub.steampipe.io/plugins/mr-destructive/cohereai/tables/cohereai_classify)

#### Suggested labels
#### </details>
