### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#77]
- [ ] idodid = fix ffmpeg using cpu instead of gpu - check git history for the old command
- [ ] connect gh actions to vm
- [ ] Update stream-deck with Projects buttons
- [ ] add the php agents python version to gh actions watcher
